### ISSUE TITLE
Does not badge icon with number of unread emails

### ISSUE THREAD

**Issue by Pointedstick** [flathub/org.mozilla.Thunderbird#10]
In a Unity or KDE Plasma environment, the Flathub Thunderbird package does not badge its icon with the number of unread emails the way distro package versions do.

**Comment by AdrianKoshka** [comment]
Could I have a screenshot example? I'm not too familiar with this "Badge".

**Comment by Exalm** [comment]
IIRC that was either an Ubuntu-specific patch or an extension...

**Comment by Pointedstick** [comment]
![spectacle j20172](https://user-images.githubusercontent.com/1097249/38463128-d0718e0a-3ab0-11e8-9b6e-bad7814d94a9.png)


> IIRC that was either an Ubuntu-specific patch or an extension...

If so, it might be nice to include this patch, provided it doesn't rely on anything Ubuntu-specific. The icon badging API it uses is a cross-distro one, I believe.

**Comment by Pointedstick** [comment]
Looks like it's an extension: "Messaging Menu and Unity Launcher integration"

However contrary to the name, it's not just for Unity; it works in KDE Plasma too (they use the same API), and also in GNOME with various extensions that implement an always-visible dock.

**Comment by AdrianKoshka** [comment]
Right, still don't know how to include extensions at build time, if someone else does and could tell me that'd be nice! (I'll look into it)

**Comment by TingPing** [comment]
@Pointedstick Run `flatpak run --log-session-bus org.mozilla.Thunderbird` to find what name it is trying to talk to.

**Comment by Exalm** [comment]
The extension can be found here: https://launchpad.net/messagingmenu-extension
The actual extension is included in the `thunderbird` package source, but the only difference is version number in `install.rdf` :D
It can be build with `./build.sh`, and the resulting file is `messagingmenu.xpi`.

But it talks to the following libraries via ctypes: `libdbusmenu`, `libunity`, `libmessaging-menu`, `libindicate`, `libgobject-2.0`, `libglib-2.0`, `libgdk-x11-2.0`.
The last 3 shouldn't be a problem, they are in runtime. But other ones aren't.
Seemingly, the only one of those is needed for unity launcher support: `libunity`, and others are for ubuntu messaging menu.

**Comment by Exalm** [comment]
Hmm, `libunity` is actually packaged on Fedora, probably for KDE. So it's probably not _that_ Ubuntu-specific.

**Comment by Exalm** [comment]
I mean, Unity/KDE/Ubuntu dock probably also need `libunity` to display badges. But that's not relevant, yes.

**Comment by AdrianKoshka** [comment]
@Pointedstick Do you still care about this issue, or should I just close it? (sorry for lack of progress on this one.)

**Comment by Pointedstick** [comment]
I still care. Don't worry about the lack of progress; this is all pretty new! Is there anything you need from me?

**Comment by AdrianKoshka** [comment]
Not at the moment, I don't think.

**Comment by ovari** [comment]
@ryanleesipes can you or someone you know please provide help? Thank you

**Comment by Erick555** [comment]
After consideration of implementing this I decided to not doing it for various reasons:

- I'm trying to make this app as close to upstream as possible while taking into account flatpak environment. Bundling 3rd party extensions is beyond that scope. Moreover this seems to be exclusive only for Ubuntu and its clones . The end goal is taking over maintenance of this app by upstream and I'm pretty certain they won't include 3rd party extensions in it.
- The fact that it's 3rd party code developed by ubuntu mean including it will make flathub app development dependent on them. This is especially important during major version upgrades when some code changes may be needed to make extension still work. With TB 68.x release there were significant changes in extensions ecosystem and many of them stopped working. I don't know if ubuntu messaging extension still works as there is no 68.x release in ubuntu yet and it's possible that flathub update would be blocked until ubuntu updates first.
- Bundling extensions dependencies like libunity requires including even more dependencies like gnome-common, intltool and vala which doesn't exist in freedesktop runtime which increases maintenance burden.

I hope above arguments make my decision clear.

**Comment by ovari** [comment]
Seems like @Erick555 is suggesting that this should be implemented upstream, i.e. in Thunderbird.

Can you please cross-reference the bug listing here from Thunderbird Bugzilla?
https://bugzilla.mozilla.org/describecomponents.cgi?product=thunderbird

Thank you

**Comment by Erick555** [comment]
@ovari I assume people interested in that functionality will report it upstream. I'm not aware if they did already or not.

**Comment by Erick555** [comment]
This was mentioned in upstream ticket but it seems that TB developers are reluctant from working on it: https://bugzilla.mozilla.org/show_bug.cgi?id=1482674#c2
