### ISSUE TITLE
"Show an alert" option not working (KDE/Plasma)

### ISSUE THREAD

**Issue by atomGit** [flathub/org.mozilla.Thunderbird#104]
the "Show an alert" notification option has never worked for me on any Linux flavor with KDE

```
alerts.useSystemBackend;true
mail.biff.alert.preview_length;40
mail.biff.alert.show_preview;true
mail.biff.alert.show_sender;true
mail.biff.alert.show_subject;true
mail.biff.show_alert;true
mail.biff.use_system_alert;true
```
i have tried toggling both `alerts.useSystemBackend` and `mail.biff.use_system_alert`

Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.66.0
Qt Version: 5.14.1
Kernel Version: 4.14.170-1-MANJARO

issue is not specific to OS, but may be specific to KDE/Plasma, though not to versions

Thunderbird: 68.5.0 (and earlier versions)

**Comment by Erick555** [comment]
Definitely works for me on KDE from Arch Linux for a last few years. Did you checked below too?

> Menu Bar > Edit > Preferences > General > Select Customize… for "Show an alert" and set "Show New Mail alert for:"

**Comment by atomGit** [comment]
yes, all those options are enabled

interesting that the notifications are working for you since we have closely related systems

**Comment by Erick555** [comment]
Did it worked for non-flatpak TB version?

**Comment by atomGit** [comment]
you just made me realize that i posted this issue to the wrong repo :)

i'm not using the flatpak version

i will let you folks decide whether to close this - and sorry about the mixup
