### ISSUE TITLE
Thunderbird creating new icon in Plank

### ISSUE THREAD

**Issue by shawn1thompson** [flathub/org.mozilla.Thunderbird#107]
Steps to reproduce:

Click on Thunderbird icon I previously created on Plank by using Elementary OS 'Add to dock'

Actual results:

Thunderbird opens with new icon to the far right

Expected results:

Thunderbird should use the existing icon

**Comment by Erick555** [comment]
Please report this to Elementary OS. I don't see anything flatpak app can do here.

**Comment by Erick555** [comment]
This fix may help here https://github.com/flathub/org.mozilla.Thunderbird/pull/187
