### ISSUE TITLE
"Manage Identity" no delete or set as deault anymore

### ISSUE THREAD

**Issue by git24hub** [flathub/org.mozilla.Thunderbird#110]
no delete or set as deault for any email identity anymore
![afqeqwe](https://user-images.githubusercontent.com/27286259/80826690-f3f4d500-8be2-11ea-9d7e-350be8bb9494.jpg)

**Comment by Erick555** [comment]
Please report this in https://bugzilla.mozilla.org/describecomponents.cgi?product=Thunderbird unless this work outside flatpak with same TB version.
