### ISSUE TITLE
How to migrate data from ~/.thunderbird to Flatpak?

### ISSUE THREAD

**Issue by kaimast** [flathub/org.mozilla.Thunderbird#112]
Hi,

Would love to move my Thunderbird install from the Debian package to this flatpak. However I do not want to reconfigure the entire thing. 

Is there a straightforward way to copy my settings from `~/.thunderbird` to `~/.var/org.mozilla.Thunderbird` ?

**Comment by Erick555** [comment]
Did you tried what is proposed in [readme](https://github.com/flathub/org.mozilla.Thunderbird#old-profile)?

**Comment by kaimast** [comment]
Not sure how I missed this but it works. Thanks so much Erick555!
