### ISSUE TITLE
display settings not being persisted across runs

### ISSUE THREAD

**Issue by whitel** [flathub/org.mozilla.Thunderbird#114]
I change the default view of the message list from default. I believe that it is not being persisted across runs of the flatpak. I think it may be just the ordering of columns rather than the set of columns.

**Comment by Erick555** [comment]
I think I heard about this before and this is upstream issue. You may try to look at their bugtracker: https://bugzilla.mozilla.org/describecomponents.cgi?product=Thunderbird

**Comment by whitel** [comment]
you appear to be correct[1], seemed so obvious as a persistence issue I didn't even check.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1622255

**Comment by Erick555** [comment]
Nothing to do here then, closing.
