### ISSUE TITLE
Any interest in flatpak-external-data-checker?

### ISSUE THREAD

**Issue by wjt** [flathub/org.mozilla.Thunderbird#116]
[flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker) supports automatically generating PRs for new Firefox releases. We at Endless used this to maintain our own [Firefox Flatpak](https://github.com/endlessm/firefox-flatpak), but now that Firefox is on Flathub that's no longer used (https://github.com/flathub/flatpak-external-data-checker/commit/8fea5b8b798e1cfc4e41124c10325a4e25ce9224).

I see this repo already contains a suspiciously similar script to update `thunderbird-sources.json`. Is there any interest in adapting [firefoxchecker.py](https://github.com/flathub/flatpak-external-data-checker/blob/master/src/checkers/firefoxchecker.py) to be usable for this package? I think the main change would be to stop hardcoding the URLs and binary names, and switch the binary tarball for the source one.

I ask because, if not, I'll just go ahead and delete the unused firefoxchecker from that repo. :-)

**Comment by Erick555** [comment]
Existing script was inspired from [this one](https://github.com/alexlarsson/firefox-flatpak/blob/master/org.mozilla.FirefoxUpstreamBinary/build_flatpak_from_url ) which I think predates firefoxchecker.

Will firefoxchecker automatically create PR with new version like other checkers do for deb sources? If yes then it indeed make maintenance bit easier however I have to point out that I don't know much python so there would be no help from my side for firefoxchecker rework.

**Comment by wjt** [comment]
Yes, here is an example: https://github.com/endlessm/firefox-flatpak/pull/75

**Comment by Erick555** [comment]
I think it's not worth the hassle to have this when thunderbird may be the only user and at some point in future it will be transited to upstream. Feel free to remove firefoxchecker code from there.
