### ISSUE TITLE
XXX Language Pack added

### ISSUE THREAD

**Issue by WhyNotHugo** [flathub/org.mozilla.Thunderbird#118]
Upon first running thunderbird, I got a prompt, and options to Enable/Cancel:

> Sinhala (si-LK_ Language Pack added: Another program on your computer installed an add-on that may affect your browser. Please choose to Enable or Cancel (to leave it disabled)

And then some other random languages. Several **dozen** times. With a 500ms delay between them.

I held down  <kbd>Esc</kbd> to skip through them, but due to the delay between popup, this took quite a long time.

These languages packs are not present on my host system, and this was super annoying. Since these packs are included in the flatpak package, these prompts should probably be skipped.

**Comment by Erick555** [comment]
Can't reproduce. Does it happen with fresh TB profile or did you re-use some old one?

Language packs aren't included in flatpak package directly but are packed in per locale extensions which should be downloaded only for default language/locale you use on host plus ones you explicitly set in flatpak config to download.

Could you show output of the following commands:
```
flatpak --version
flatpak config
localectl
```

**Comment by WhyNotHugo** [comment]
This was a fresh profile, it's the first time I installed thunderbird via flatpak (I'd used thunderbird in the past, but had `rm -rf ~/.thunderbird` since.

Flatpak is pretty much set to its factory defaults too.

```console
$ flatpak --version
Flatpak 1.7.2

$ flatpak config --list
languages: *unset* (default: *all*)
extra-languages: *unset*

$  localectl
   System Locale: LANG=C
       VC Keymap: n/a
      X11 Layout: n/a

$ env | grep LC  # Since you mentioned the host locale being relevant
LC_COLLATE=C
LC_MONETARY=en_US.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_DK.UTF-8
```

**Comment by Erick555** [comment]
```
$  localectl
   System Locale: LANG=C
```

```
$ flatpak config --list
languages: *unset* (default: *all*)
```
Ok, so I think the problem is shown above. You don't have global locale set properly on host and flatpak can't detect it thus it downloads everything. Try setting:
`localectl set-locale LANG=en_GB.UTF-8` (or anything else as you wish)
then reboot, remove & install thunderbird flatpak, remove (or move somewhere else) `~/.var/app/org.mozilla.Thunderbird`.

**Comment by Erick555** [comment]
Instead of `localectl set-locale LANG=en_GB.UTF-8` you may  just set `flatpak config --set languages en` if you want to fix just flatpak.

**Comment by WhyNotHugo** [comment]
`LANG` is set for my user though. Maybe flatpak ought to pick that app? This suffices for all other apps.

> you may just set flatpak config --set languages en if you want to fix just flatpak.

This doesn't work (`root` has no password). Maybe just bail if root has not password?

```console
$ flatpak config --set languages en
==== AUTHENTICATING FOR org.freedesktop.Flatpak.configure ====
Authentication is required to configure software installation
Authenticating as: root
Password:
```

`sudo flatpak config --set languages` fixed it -- no prompts when re-starting from scratch :slightly_smiling_face:

I did notice that both the `en_US` and `en_GB` language packs are installed though -- I'm guessing that's unavoidable?

Thanks!

**Comment by Erick555** [comment]
> This doesn't work (root has no password). Maybe just bail if root has not password?

Without sudo it should invoke [polkit](https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html) to prompt for authentication. It's possible that for some reason polkit doesn't work on your system.

> I did notice that both the en_US and en_GB language packs are installed though -- I'm guessing that's unavoidable?

Yes, that's unavoidable but I hope it's not a big deal.

**Comment by Erick555** [comment]
> LANG is set for my user though. Maybe flatpak ought to pick that app? This suffices for all other apps.

I don't know how locale detection in flatpak works under the hood so it's better to ask about this at https://github.com/flatpak/flatpak/issues

**Comment by WhyNotHugo** [comment]
Oh, yeah, polkit it something I never really setup up, so that one's on me.

> Yes, that's unavoidable but I hope it's not a big deal.

Not really, I'm sure there's better use of your time :)

Thanks, I appreciate you time and help here!
