### ISSUE TITLE
Open Profile Directory doesn't work

### ISSUE THREAD

**Issue by lukashass** [flathub/org.mozilla.Thunderbird#123]
## Steps to reproduce

1. Click on the menu button ![Menu](https://user-images.githubusercontent.com/32853499/87877976-b170b680-c9e1-11ea-8971-78c04d627582.png) , then go to `Help` and select `Troubleshooting Information`.
1. Click on `Open Directory` in *Profile Directory*.
1. Your Thunderbird profile folder should open in File Browser, but nothing happens.

**Comment by Erick555** [comment]
Yes, this is flatpak limitation. The same is true for firefox flatpak. I think we can't fix this here.

**Comment by ovari** [comment]
Have you tried using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)?

In `Filesystem`, is `All system files` enabled? Does that help? If not, try enabling the other options. Please advise which option works.

Thank you

**Comment by fabriciojardim** [comment]
I had the same issue following the instructions to backup Thunderbird. The workaround was to copy the profile directory from the location below:
`~/var/org.mozilla.Thunderbird/.profile`
Can someone familiar with this please confirm this the correct directory?

Thanks.

**Comment by Erick555** [comment]
Yes ~/.var/org.mozilla.Thunderbird/.thunderbird is where TB flatpak profiles are stored.

**Comment by xduugu** [comment]
The upstream issue can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1625111).

Does it make sense to track all these upstream issues downstream?

**Comment by Erick555** [comment]
No, but I wasn't aware of the upstream ticket and wasn't certain who is responsible. It may be worth to record known upstream flatpak issues in readme to prevent recurring questions though.

**Comment by xduugu** [comment]
Ah okay, I thought you knew it as it was labeled as "upstream". I was just wondering about all these "upstream" issues, even for hidden features like the wayland support.

**Comment by Erick555** [comment]
I somewhat knew but wasn't 100% percent sure. Also if it wasn't tracked upstream then there would be no path forward for this.

**Comment by Erick555** [comment]
Info about this is now in [readme](https://github.com/flathub/org.mozilla.Thunderbird/commit/acfa9a00cc69bde7e7a45fb462d7770306d06e50).

**Comment by darman96** [comment]
Enabling `All user files` in Flatseal did kinda work.
It opened the dialog but in `~/.thunderbird` instead of the actual profiles folder: `~/.var/app/org.mozilla.Thunderbird/.thunderbird`

As a workaround I made a symlink from `~/.var/app/org.mozilla.Thunderbird/.thunderbird` to `~/.thunderbird`
