### ISSUE TITLE
Beta Track not on Beta

### ISSUE THREAD

**Issue by ryanleesipes** [flathub/org.mozilla.Thunderbird#136]
Saw the following post on issue #120. I installed the Beta but it is currently at 78.2.1, which isn't Beta. This is a strange release cycle, given that stable is not on the 78.x yet - but we should update the beta track to current beta release.

Original post:

>Yes, first upload will be available within few hours. After that you can do:
>
>For local user installation:
>```
>flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
>flatpak update --appstream
>flatpak install --user flathub-beta org.mozilla.Thunderbird//beta
>```
>
>For system-wide installation:
>```
>flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
>flatpak update --appstream
>flatpak install flathub-beta org.mozilla.Thunderbird//beta
>```
>
>Then:
>`flatpak run org.mozilla.Thunderbird//beta`

_Originally posted by @Erick555 in https://github.com/flathub/org.mozilla.Thunderbird/issues/120#issuecomment-660550095_

**Comment by Erick555** [comment]
Yes, currently `beta` as in flatpak means something different than `beta` as in upstream, see https://github.com/flathub/org.mozilla.Thunderbird/issues/128#issuecomment-669249930 .

**Comment by Erick555** [comment]
I re-open as something upstream to consider after maintenance takeover.

**Comment by Erick555** [comment]
Flatpak is now managed by Thunderbird team. Closing
