### ISSUE TITLE
Add MOZ_ENABLE_WAYLAND=1 for actual Wayland support

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/org.mozilla.Thunderbird#146]
Related to https://github.com/flathub/org.mozilla.Thunderbird/issues/75, `--socket=wayland` is useless when `MOZ_ENABLE_WAYLAND` isn't enabled. It would be better if the manifest automatically enables it by default.

**Comment by Erick555** [comment]
Upstream doesn't support wayland by default and it causes some thing are broken: https://github.com/flathub/org.mozilla.Thunderbird/issues/134 https://github.com/flathub/org.mozilla.Thunderbird/issues/109 thus we shouldn't enable it for now.
