### ISSUE TITLE
Enable `filesystem=host` by default

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#156]
Should `filesystem=host` be enabled by default?

Screenshot below is from [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)
![image](https://user-images.githubusercontent.com/17465872/100137838-32384580-2ee1-11eb-990f-1bd25c11c31f.png)

Without this setting enabled, files from USB sticks can't be attached to emails.

What do you think?

Thank you

Edit: The following programs have `filesystem=host` be enabled by default:
* [GNU Image Manipulation Program](https://flathub.org/apps/details/org.gimp.GIMP)
* [MuseScore](https://flathub.org/apps/details/org.musescore.MuseScore)
* [VLC](https://flathub.org/apps/details/org.videolan.VLC)

Thank you once again

**Comment by Erick555** [comment]
`filesystem=host` makes whole sandboxing rather pointless as it's trivial to escape the sandbox and gain arbitrary code execution on host. Moreover TB uses `xdg-desktop-portal` for adding attachments and I'm able to add attachment from mounted usb stick just fine so I can't reproduce this issue.
