### ISSUE TITLE
GPG key lookup with adress not working

### ISSUE THREAD

**Issue by t2d** [flathub/org.mozilla.Thunderbird#157]
This is the same bug as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973697 and https://gitlab.tails.boum.org/tails/tails/-/issues/17147#note_159090, but for flatpak.

The error shown in the Error Console is
```
Error: Error: Could not find libresolv in any of libresolv.9.so,libresolv.so Exception: Error: couldn't open library libresolv.so: libresolv.so: cannot open shared object file: No such file or directory
```

Fix:
```
flatpak list --app --columns=application,runtime
Application ID                         Runtime
org.mozilla.Thunderbird                org.freedesktop.Platform/x86_64/19.08

cd /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/lib/x86_64-linux-gnu/
sudo ln -s libresolv.so.2 libresolv.so
```
Should this be reported to the runtime somehow or should Thunderbird ask for another path?

**Comment by Erick555** [comment]
`libresolv.so` is a development symlink supposed to be used only at build time. That's why flatpak ships it only is Sdk and not in Platform and debian splits it to `-dev` package.

So ultimately this is TB issue that should be reported there (if not already) but I'll try to make this symlink in `/app/lib` for a quick workaround. Thx for reporting.

**Comment by Erick555** [comment]
@t2d please try if:
```
cd /var/lib/flatpak/app/org.mozilla.Thunderbird/current/active/files/lib
sudo ln -s /usr/lib/x86_64-linux-gnu/libresolv.so.2 libresolv.so
```
works for you (remember to delete the previous symlink you created.

**Comment by t2d** [comment]
I dont have `/usr/lib/x86_64-linux-gnu/libresolv.so.2` on OpenSuse Tumbleweed. I just have `/lib64/libresolv.so.2` and `/lib/libresolv.so.2`, but linking neither of these works.

**Comment by Erick555** [comment]
@t2d this symlink is supposed to work only in flatpak environment, whatever you have in your system is irrelevant, please test commands I provided above.

**Comment by t2d** [comment]
Thank you for the explanation. I now executed the commands as you said. Still, it sadly doesn't work and the error is the same as stated above.

**Comment by Erick555** [comment]
Perhaps we need to patch the source then.

**Comment by Erick555** [comment]
Upstream ticket is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1634053
