### ISSUE TITLE
Usage of external GnuPG does not seem to work

### ISSUE THREAD

**Issue by func0der** [flathub/org.mozilla.Thunderbird#163]
Hey fellas,

it seems that a GnuPG setup according to this guide is not possible with the Flatpak version of Thunderbird: https://wiki.mozilla.org/Thunderbird:OpenPGP:Smartcards

It basically should use the GnuPG agent of the system for decryption.

Test setup: 
1. Put your PGP key into your keychain
2. Follow the instructions of the links above
    * `mail.openpgp.allow_external_gnupg: true`
    * Add key -> GnuPG -> Add key ID
    * Add public key of ID to internal Thunderbird OpenPGP Manager
3. Create a new email and save it is drafts
4. Try to open said draft
5. Fail

Setup:
* Pop_OS! 20.04
* Thunderbird 78.6.0
* Flatpak 1.6.5

I tried to get some logs for this behavior, but I can not find anything.

Can anybody please confirm/deny that this setup works with this Flatpak version of Thunderbird?

**Comment by Erick555** [comment]
It was [reported to be working](https://github.com/flathub/org.mozilla.Thunderbird/pull/149#issuecomment-719831494) before. You need gpg-agent to be running before you start thunderbird. Maybe @xduugu can provide more info.

**Comment by func0der** [comment]
Okay, this was actually my bad.

I do not know why, but if I create an ECC key in the TB OpenPGP key manager, export that private key and try to import that one into the gpg store of my OS, it can not read the key properly or better say "bad passphrase".

If I create the exact same key with gpg on my OS (ECC with Curve 25519), import that one into Thunderbird and export it again, it works.
This is soo strange, but I guess it is a Thunderbird bug and has nothing to do with the Flatpak.

Thanks for the input, @Erick555  :)

**Comment by func0der** [comment]
At this point in time, it seems to be a bug in rnp: For reference: https://github.com/rnpgp/rnp/issues/1018
