### ISSUE TITLE
Thunderbird isn't built against the freedesktop runtime

### ISSUE THREAD

**Issue by AdrianKoshka** [flathub/org.mozilla.Thunderbird#17]
Don't know if this is something to be concerned about, but I thought apps on flathub had to be built against the freedesktop runtime instead.

**Comment by TingPing** [comment]
>  I thought apps on flathub had to be built against the freedesktop runtime instead.

GNOME, KDE, and FDO runtimes are hosted on and usable on Flathub. Using fdo just *might* be a smaller install for some users depending on how much you need to bundle.
