### ISSUE TITLE
Thunderbird doesn't start

### ISSUE THREAD

**Issue by t2d** [flathub/org.mozilla.Thunderbird#172]
When I click on the Thunderbird icon in Ubuntu 20.04, it doesn't start.

```
# head /var/lib/flatpak/exports/share/applications/org.mozilla.Thunderbird.desktop 
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=thunderbird --file-forwarding org.mozilla.Thunderbird @@u %u @@
Icon=org.mozilla.Thunderbird
Terminal=false
Type=Application
MimeType=message/rfc822;x-scheme-handler/mailto;
StartupNotify=false
Categories=Network;Email;
```
If I copy the Exec line to terminal it also doesn't work.
```
❯ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=thunderbird --file-forwarding org.mozilla.Thunderbird @@u %u @@
Gtk-Message: 16:37:36.104: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:37:36.104: Failed to load module "canberra-gtk-module"
```
Then nothing.

If I remove `%u` it starts fine.
```
❯ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=thunderbird --file-forwarding org.mozilla.Thunderbird  @@
Gtk-Message: 16:39:37.307: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:39:37.308: Failed to load module "canberra-gtk-module"
```
Starts fine.

But it doen't help if I adjust the Exec line in `/var/lib/flatpak/exports/share/applications/org.mozilla.Thunderbird.desktop ` or `~/.local/share/flatpak/exports/share/applications/org.mozilla.Thunderbird.desktop` in the same way.

What else can I do? Thanks in advance.

**Comment by Erick555** [comment]
It works for me on ubuntu 20.10 when clicking in desktop icon. The command from destkop file doesn't work from terminal with `%u` but it's normal as that command is supposed to be run only from desktop file. Executing `flatpak run org.mozilla.Thunderbird` in terminal works fine.

What flatpak version is this? `flatpak --version`

**Comment by t2d** [comment]
I had two versions of Thunderbird flatpak installed. One in user, one in system. The command line did start the system one, but the tray icon the user one. After removing the user one everything is working as expected.
