### ISSUE TITLE
Appchooser not showing any options except Thunderbird itself when interacting with files.

### ISSUE THREAD

**Issue by PhilippKuntschik** [flathub/org.mozilla.Thunderbird#182]
I am not 100% sure if this is the right place since I still do not fully understand how flatpak permissions and desktop portals play together. The testing I did the last hours led me to open this issue

The symptoms are, that the appchooser dialog does only show thunderbird as an option to open pdf files. This leads to create a new draft including the pdf as an attachment. I expect to have various options from apps installed with and without flatpak to choose from.

![image](https://user-images.githubusercontent.com/9104613/120283003-00060700-c2bb-11eb-803f-73135823c136.png)
![image](https://user-images.githubusercontent.com/9104613/120283042-0d22f600-c2bb-11eb-8726-c059d89dc461.png)

To narrow down if it is an issue with my system, the desktop portal implementation or the flatpak-app, I tried opening a pdf with other apps as well. Zotero for example let me chose Evince (non flatpak) as an opening option, leading to my guess that it is neither my system, nor the desktop portal imlementation.

System is Xubuntu 21.04 with updated software.

Please let me know if you need any information.

**Comment by Erick555** [comment]
In order to use portal you need to chose _System Handler_ option, the _Other_ won't work in flatpak. The former should show available apps on system that can handle attachment or open it automatically. I confirmed it working on Kubntu 21.04 with flatpak 1.10.2

Note that I saw some regression with flatpak 1.11.1 so you you installed it from ppa I recommend to go back to distro version.

**Comment by PhilippKuntschik** [comment]
thanks for the reply @Erick555.

I downgraded to flatpak 1.10.2 and can confirm that it works. do you know if this is a known issue? should this be reported upstream?

**Comment by macmpi** [comment]
issues persists on elementary 6.1 / flatpak 1.12.4 / Thunderbird 91.5.1 (flatpak)
I can not open any attachment, whatever attachment setting (System Handler or Always ask).
Thanks for any tip.

**Comment by Erick555** [comment]
What is xdg-desktop-portal version? It should be 1.10.0 at minimum.

**Comment by Erick555** [comment]
You have to either downgrade flatpak below 1.11 or upgrade xdg-desktop-portal above 1.10

**Comment by macmpi** [comment]
```
/usr/libexec/xdg-desktop-portal --version
xdg-desktop-portal 1.7.2
```
not sure why I have so many portal-related stuff on elementary 6.1:
```
/usr/lib/systemd/user/xdg-desktop-portal-gtk.service
/usr/lib/systemd/user/xdg-desktop-portal-pantheon.service
/usr/lib/systemd/user/io.elementary.settings-daemon.xdg-desktop-portal.service
/usr/lib/systemd/user/xdg-desktop-portal.service
/usr/lib/systemd/user/io.elementary.files.xdg-desktop-portal.service
/usr/lib/x86_64-linux-gnu/xdg-desktop-portal-pantheon
/usr/lib/x86_64-linux-gnu/io.elementary.files.xdg-desktop-portal
/usr/lib/x86_64-linux-gnu/io.elementary.settings-daemon.xdg-desktop-portal
/usr/libexec/xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-gtk
/usr/libexec/xdg-desktop-portal-validate-icon
```

**Comment by Erick555** [comment]
I think it's best to raise this issue regarding xdg-desktop-portal update to Elementary 6.1 developers.

**Comment by Erick555** [comment]
BTW: combination of flatpak 1.12.4 + xdg-desktop-portal 1.7.2 is suspiciously close to [flatpak PPA for ubuntu bionic](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak?field.series_filter=bionic) so if you use it then please disable and reinstall thos packages from distro repos.

**Comment by macmpi** [comment]
Thanks, but no, I do not have that PPA installed.

**Comment by Erick555** [comment]
Then maybe Elementary reuse packages from PPA?

**Comment by ovari** [comment]
Uninstalled Thunderbird on both Linux Mint 20.3 Cinnamon and LMDE 5 operating systems before installing Thunderbird flatpak.

Same situation with Linux Mint 20.3 Cinnamon and LMDE 5.

![image](https://user-images.githubusercontent.com/17465872/159147827-0057c7ae-849f-45bf-9d75-57b748ae7658.png)

![image](https://user-images.githubusercontent.com/17465872/159147829-45271e8e-a143-42f1-99bd-2b456f3372ea.png)

![image](https://user-images.githubusercontent.com/17465872/159147832-cf943cd7-56c9-47cd-9d07-89b02cddd64f.png)

Does this mean it isn't an Elementary issue as it also happens on [Linux Mint](https://linuxmint.com/download.php) (Ubuntu base) and [LMDE](https://linuxmint.com/download_lmde.php) (Debian base)?

Thank you

**Comment by Erick555** [comment]
This is problem for every distro which ships incompatible versions of `flatpak` and `xdg-desktop-portal`

**Comment by mzilhao** [comment]
I'm seeing this same issue on Fedora 36. Both `flatpak` and  `xdg-desktop-portal` are above version 1.12:

Name         : flatpak
Version      : 1.12.7

Name         : xdg-desktop-portal
Version      : 1.12.3

**Comment by Erick555** [comment]
Does it work for any other flatpak?

**Comment by mzilhao** [comment]
OK, I've now installed the latest Thunderbird version on flathub (91.8.0) and it seems to be working fine.

**Comment by dagdrommer** [comment]
Hello there. For me it's not working anymore in Thunderbird from flathub (91.10.0).

**Comment by Erick555** [comment]
Does it work for any other flatpak app (firefox for example)?

**Comment by dagdrommer** [comment]
I can confirm it for firefox aswell.

**Comment by ubiquando** [comment]
Hello, I still have the same problem with thunderbird 102.5.1 and xdg-desktop-portal 1.15.0-4, fedora 37.
It seems I should uninstall it from flatpak and reinstall with dnf but I'm afraid I would loose things...
