### ISSUE TITLE
Beta 91: Language packs missing signature

### ISSUE THREAD

**Issue by Tibladar** [flathub/org.mozilla.Thunderbird#197]
When running the current beta 91.1.0 only the default english language is installed and can be used (new profile).
`org.mozilla.Thunderbird.Locale` downloaded the correct language file for my system (`langpack-de@thunderbird.mozilla.org.xpi`)

The developer console shows this each run:
![image](https://user-images.githubusercontent.com/52620063/132944142-e2271b1b-4bad-4ae9-9459-0169ab825725.png)
Probably because the language files are missing on disk (maybe the cause why Thunderbird stalls for a second at start)

The language "de" I want to use is not listed in these logs

Manually installing the langpack-de file does nothing and the log contains:
```
addons.xpi-utils	WARN	Add-on langpack-de@thunderbird.mozilla.org is not correctly signed. 2
addons.xpi	        WARN	Invalid XPI: signature is required but missing
```

Flatpak:
```
$ flatpak --version
Flatpak 1.11.2

$ flatpak config --list
languages: de (default: de)
extra-languages: *unset*
```

**Comment by Erick555** [comment]
Thx, this is known upstream bug which should be fixed in next release: https://bugzilla.mozilla.org/show_bug.cgi?id=1727113
