### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.mozilla.Thunderbird#2]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by Pointedstick** [comment]
...And also some text for the SUmmary and Description fields! And preferably any additions to the AppStream file would be submitted upstream.

**Comment by AdrianKoshka** [comment]
Hrmm, will look into the AppStream data stuff and screenshots, not too familiar with Appstream at all.

**Comment by AdrianKoshka** [comment]
Thought I already had a [screenshot](https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.appdata.xml#L20)

**Comment by Pointedstick** [comment]
Sorry still not fixed. The file in its current form does not pass `appstreamcli validate`:

```
$  (master) appstreamcli validate org.mozilla.Thunderbird.appdata.xml 
E - org.mozilla.Thunderbird.appdata.xml:org.mozilla.Thunderbird
    The component contains a screenshot without any images.

Validation failed: errors: 1
```

it should look like this:

```
	<screenshots>
		<screenshot type="default">
			<image>https://i.imgur.com/W3zlfng.png</image>
		</screenshot>
	</screenshots>
```

**Comment by TingPing** [comment]
Passes fine here, `appstream-util` version 0.7.7. Perhaps your version is outdated?

**Comment by Pointedstick** [comment]
Actually it's the opposite; mine is newer:

```
$ appstreamcli --version
AppStream CLI tool version: 0.11.3
```
