### ISSUE TITLE
Website button URL to official Thunderbird website

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#20]
This suggestion relates to the 'Website' button at:
https://flathub.org/apps/details/org.mozilla.Thunderbird
Suggestion:
Change "https://www.mozilla.org/en-US/thunderbird/" to "https://www.thunderbird.net/"

What do you think?

Thank you

**Comment by AdrianKoshka** [comment]
I'm guessing this re-directs to the propper language page rather than just dumping the person to the `en-US` page?

**Comment by ovari** [comment]
@AdrianKoshka Yes, redirecting to the proper language page is another benefit.

**Comment by AdrianKoshka** [comment]
Will do then.

**Comment by AdrianKoshka** [comment]
done with this commit ca8048d7cf344113f41415811ed9d6f38b889705

**Comment by ovari** [comment]
@AdrianKoshka Thank you for your prompt commit.
Are you able to accept:
https://github.com/flathub/org.mozilla.Thunderbird/pull/21
Thank you
