### ISSUE TITLE
Versions 91.3.1 and 91.3.2 unusable on Ubuntu 20.04

### ISSUE THREAD

**Issue by bayonne** [flathub/org.mozilla.Thunderbird#212]
Versions 91.3.1 and 91.3.2 are unusable for me on Ubuntu 20.04; memory use skyrockets.
Had to revert to commit cb31d2e15c11697356646123dd44c80522fc60430d08c1b9ded4a71c5b813c0d.

**Comment by Erick555** [comment]
Thx for the report. Nothing changed in those except version bump so you may try reporting it to [upstream](https://bugzilla.mozilla.org/describecomponents.cgi?product=Thunderbird). I can't reproduce those issues myself.

**Comment by dgcampea** [comment]
@bayonne Are you using ublock extension (or any other extension) within thunderbird?

**Comment by bayonne** [comment]
> @bayonne Are you using ublock extension (or any other extension) within thunderbird?

Yes, version 1.38.6 of uBlock is installed.

**Comment by revco8** [comment]
I had a similar problem and when uninstalling all language packs in TB the problem disappeared. Worth a try?

**Comment by dgcampea** [comment]
I've noticed the slowdowns happen if I open the Settings tab, although if started in safe-mode there's no problems at all.
It's also probably not related to ublock as disabling it doesn't fix the bug.

**Comment by Erick555** [comment]
Apparently upstream is [aware](https://thunderbird.topicbox.com/groups/planning/T23f0029e919e9ead/notice-thunderbird-91-4-0-available) about this issue and hopefully 91.4.0 release will fix it
