### ISSUE TITLE
Use xdg file chooser (or mention in README)

### ISSUE THREAD

**Issue by kaimast** [flathub/org.mozilla.Thunderbird#214]
If you go to Thunderbird's config editor and enable `widget.use-xdg-desktop-portal` it will use the XDG file chooser portal. 

I am not sure if that is something we can enable by default, but maybe mention it in the README?

**Comment by Erick555** [comment]
Flatpak use portal by default even without this option enabled.

**Comment by kaimast** [comment]
Strange. Maybe my configuration was out of date for some reason...

**Comment by kaimast** [comment]
One more data point: I'm on a fresh install on Arch (I was on Ubuntu before) and it is not enabled by default.

**Comment by Erick555** [comment]
To clarify: `widget.use-xdg-desktop-portal` is irrelevant for flatpak. I have it on false and portals work.
