### ISSUE TITLE
Can't change local folders location

### ISSUE THREAD

**Issue by pgalbraith** [flathub/org.mozilla.Thunderbird#227]
In account settings, I cannot change the folder location of "Local Folders".

**Comment by Erick555** [comment]
Did you try to type or paste new folder location address?

**Comment by Erick555** [comment]
Anyway it works for me - under local directory I clicked on browse then selected new folder. App proposed restart and after that new folder was active.

**Comment by pgalbraith** [comment]
I can't manually edit the field, I have to click browser and choose a folder.  When I do (and restart) it doesn't actually change, though, it's still locked into a flatpak directory.  I had to uninstall the flatpak version and install from deb package instead (I'm running Pop!_OS 21.10) and only then could I specify the local folders location.

**Comment by Erick555** [comment]
Is there anything special about the new location you want to use? Is it under `/home/<user>/.var/app/org.mozilla.Thunderbird`? `/home/<user>`? Different filesystem?

**Comment by pgalbraith** [comment]
I keep it under a DropBox folder in my home directory, but I don't think there's anything special about that.  Thunderbird from the deb packages certainly has no problem with it.

**Comment by pgalbraith** [comment]
Ahhhh maybe this is just me not understanding flatpak...does /run/flatpak/doc/xxxxxxxx/ typically map to my user home directory?

**Comment by Erick555** [comment]
It maps it through file portal which uses fuse filesystem but I think thunderbird may not like this format for its internal configuration. You my try allowing this path directly in sandbox with: `flatpak override --user --filesystem=~/<path/to/folder/ org.mozilla.Thunderbird` ie. `flatpak override --user --filesystem=~/Dropbox/Localmail org.mozilla.Thunderbird`. The start app and try changing local mail folder again.

**Comment by pgalbraith** [comment]
Ok so I've figured out that it is actually working, I was just thrown off by the fuse filesystem.  This is what I see in the settings:

![image](https://user-images.githubusercontent.com/19995454/154398509-3a9e1b55-5fed-4557-af36-05c29004ae37.png)

But that is actually mapping to `/home/paul/Dropbox/Thunderbird/Local Folders`.  If I did the override that you've suggested, what would change?

**Comment by Erick555** [comment]
If you do override (and adjust path in settings) then thunderbird will see this path directly as `/home/paul/Dropbox/Thunderbird/Local Folders` without fuse intermediary. If it works as is then it's not necessary.

**Comment by pgalbraith** [comment]
Ok well I'm happy, though really I think the correct folder should be displayed right out of the gate.  Not sure if that's worth tracking as an issue here or not, though.

**Comment by Erick555** [comment]
Without override thunderbird can access this path only through fuse portal so the path you see is the only one that exist from app perspective.

**Comment by pgalbraith** [comment]
Ok so it sounds like doing that manual override is a good workaround to the issue, but it's still an issue nonetheless.

**Comment by Erick555** [comment]
The issue is not-actionable though. Accessing files through portals is fundamental for flatpak apps.

**Comment by pgalbraith** [comment]
@Erick555 just because it's not an easy fix, doesn't mean it's not an issue.

**Comment by Erick555** [comment]
I didn't say it's not an easy fix but it's not actionable -> not fixable.

**Comment by pgalbraith** [comment]
@Erick555 I don't believe this is the way that the Thunderbird devs intend it to work.  Things like this are always actionable, but may be a heavy lift.  I think it's a disservice to both the devs and users to pretend that there's no problem here.  Unfortunately, it is a very deeply embedded problem with no easy fix.  Things like this are usually worth keeping track of.

**Comment by pgalbraith** [comment]
This is an issue with the flatpak packaging of Thunderbird.  It is *not* working as intended.

**Comment by Erick555** [comment]
The please describe what doesn't work and what you propose to fix this.

**Comment by pgalbraith** [comment]
@Erick555 the issue is that Thunderbird is not displaying the intended information in the dialog box.  I do not have a solution to this problem, I am merely pointing out the *issue*.

**Comment by pgalbraith** [comment]
The whole point of my being stubborn about this is that, just because there's no obvious or easy *solution*, does not in any way change the fact that there is an *issue*.

**Comment by Erick555** [comment]
Thunderbird is accessing `/run/flatpak/doc/ `and the same path is shown in your screenshot. Thunderbird can't access `/home/paul/Dropbox/Thunderbird because it's not available for the app and obviously it can't show unavailable path in dialog or even know about.

All flatpak apps are containerized and filesystem inside container is totally different than filesystem on your host. This is by design not a bug somewhere. For thunderbird there is **no issue** and for flatpak there is **no issue** either which is why there won't be easy or hard solution for it. There won't be any solution at all.

There is nothing else to add here from me. I hope this clears all points.

**Comment by pgalbraith** [comment]
No it really doesn't.  For the user, there is an issue in the interface and you're glossing over it because you don't know how to do anything about it.  The dialog in the screen shot above is not showing the correct path/folder.  Yes, I understand why.  Understanding why does not make it correct.

**Comment by Erick555** [comment]
Please elevate this to [flatpak](https://github.com/flatpak/flatpak/issues). I'm sorry but I really can't help you here.

**Comment by pgalbraith** [comment]
That's my whole point, this is a real issue, not easily solved, and it really points to an underlying problem in flatpak that really impact a lot of applications.  An issue should be opened there, and this issue linked to it as parent.  I'd expect you to do that as you know a lot more about flatpak than I do.  Tracking the issues is the first step in getting attention to large problems like this.  Don't sweep it under the rug.

**Comment by Erick555** [comment]
All I know about flatpak tells it's unchangeable. You can disagree but expecting I would spend time representing your opinion which I don't share is a bit too much.

**Comment by pgalbraith** [comment]
Interesting, so you believe that when a user in this situation selects a folder under their home directory, it in fact ***should*** display in the UI as `/run/flatpak/...`.  In that case, yes, we definitely don't share the same opinion.

**Comment by Erick555** [comment]
Yes, this is exactly what I'm telling you.
