### ISSUE TITLE
Flatpak for Thunderbird Beta

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#23]
Please provide a Thunderbird Beta flatpak

Do the following links help:
https://www.thunderbird.net/channel/
https://www.thunderbird.net/thunderbird/beta/all/

Thank you

**Comment by AdrianKoshka** [comment]
If I remember correctly, flathub doesn't do development snapshots, and I think this would fall under that. Going to @TingPing for confirmation.

**Comment by TingPing** [comment]
Indeed it does not currently. It shouldn't be hard to adapt it and host it elsewhere though.

**Comment by AdrianKoshka** [comment]
Indeed, I'll close this issue and #24
