### ISSUE TITLE
Add up-to-date screenshot

### ISSUE THREAD

**Issue by theoholl** [flathub/org.mozilla.Thunderbird#236]
The [screenshot on Flathub](https://dl.flathub.org/repo/screenshots/org.mozilla.Thunderbird-stable/752x423/org.mozilla.Thunderbird-5cac40e88f7af879d58265c3c6214f1e.png) is really old and I think this might influence a user's decision when choosing an email software. Can we add a more up-to-date screenshot?

**Comment by Erick555** [comment]
I agree. If you can find me modern screenshot valid for appstream spec then I can use it.

**Comment by ovari** [comment]
@Sancus would you please advise a url to a screenshot of Thunderbird for GNU/Linux valid for [appstream](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info) spec? Thank you
