### ISSUE TITLE
Thunderbird (flatpak) could not find existing profile.

### ISSUE THREAD

**Issue by g-reno** [flathub/org.mozilla.Thunderbird#239]
Thunderbird 91.9.0 (64-bit)
Followed the steps in the README/Known Issues regarding using an old profile with the new FlatPak version of Thunderbird.  Moved the old profile under the new area under .var/ and issued the flatpak command which brought up the profile chooser.  The old profile was nowhere to be found.  What I had to do to get the old profile into the profile chooser was to create a new entry for it in the profiles.ini file.  Then and only then did the old profile appear in the profile chooser and Thunderbird then began using it.

**Comment by Erick555** [comment]
> What I had to do to get the old profile into the profile chooser was to create a new entry for it in the profiles.ini file.

Was there no old profile entry in profiles.ini or how then new one was different than the old?

**Comment by g-reno** [comment]
This was a fresh Fedora 36 install that mounted my existing /home partition on another drive.  The previous version of Thunderbird that I was using prior to F36 was from RPM.
Once installed I enabled full flathub repo and installed Thunderbird (flatpak) from it.
Went to about:profiles and noticed right away that paths looked different and there was no entry for old profile anywhere.
So came here and saw the Known Issues about old profile and that's when I discovered it didn't work without manually putting an entry in profiles.ini.

**Comment by Erick555** [comment]
So the most effortless migration path from rpm to flatpak would be to clear all files under `.var/app/org.mozilla.Thunderbird/*` then copy/move `.thunderbird` folder inside `.var/app/org.mozilla.Thunderbird`. After that either TB should automatically use yours old profile or you can chose it manually from `org.mozilla.Thunderbird -P`.

**Comment by g-reno** [comment]
That might work better because you're moving the entire  .thunderbird directory to a path that this flatpak version knows.
Just copying/moving the old profile in old  .thunderbird directory into the new path wasn't enough by itself.

**Comment by g-reno** [comment]
In my instance, any copying was out of the question.  Had to be a move because .thunderbird was 50G+.  Didn't have that much space for a copy.

**Comment by Erick555** [comment]
Hm, maybe the readme is unclear in this regard but the intent was to always copy/move entire  `.thunderbird` not just profile folder from inside. I'll try to improve it.
