### ISSUE TITLE
Unable to use letsencrypt certificate

### ISSUE THREAD

**Issue by givname** [flathub/org.mozilla.Thunderbird#241]
When i try to send a message, i cannot accept the certificate (Letsencrypt) or add a rule for it, when i use the pop shop deb it works fine. The address suggested looks like domain.tld:465. I looked at it and it claims *.yourpserver.net as a name and dns. I tried removing the :465 and then it shows the correct name and dns, thunderbird also says its correct but i cannot continue from there.

**Comment by Erick555** [comment]
Could you check if the certificate can be accepted in firefox flatpak?

**Comment by givname** [comment]
Just installed  firefox flatpak and its working fine on my domain when using https

**Comment by givname** [comment]
I looked futher into this and it seems to work properly with letsencrypt now. Since i am using Plesk there still seems to be an issue accepting self signed certificates (which was the case since our letsencrypt didnt work any more after Plesk update and then it uses self signed cert as fallback).

**Comment by givname** [comment]
A recent flatpak update seems to have the issue resolved.

**Comment by Erick555** [comment]
That's great, thx for reporting.
