### ISSUE TITLE
no resize cursor

### ISSUE THREAD

**Issue by RafalSkolasinski** [flathub/org.mozilla.Thunderbird#245]
There is no resize cursor when hovering mouse around edge of the window. Happening on Gnome on Ubuntu 22.04 both on Wayland and X11. 

After downgrade to commit `0d8e9248660c81da82b0282f7b3950d3b5196f32690c5b4b38ee218355aed17f` it works again as it should.

**Comment by Erick555** [comment]
I don't see such commit in git or ostree repos. How exactly did you downgrade. Also I don't believe app update could affect resizing windows which is handled by window manager from host. It work fine for me on KDE and X11.

**Comment by RafalSkolasinski** [comment]
I did run
```
sudo flatpak update --commit=0d8e9248660c81da82b0282f7b3950d3b5196f32690c5b4b38ee218355aed17f org.mozilla.firefox
```

**Comment by RafalSkolasinski** [comment]
ok, I see my mistake, wrong repo. sorry :D

**Comment by RafalSkolasinski** [comment]
final question, where to report on org.mozilla.firefox? I somehow cannot find a right repo...

**Comment by Erick555** [comment]
FF flatpak is maintained directly by mozilla so issues should be reported at [bugzilla](https://bugzilla.mozilla.org/home).
