### ISSUE TITLE
Add ‘Issues’ button

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#26]
Add an ‘Issues’ button after the ‘Website’ button on:
https://flathub.org/apps/details/org.mozilla.Thunderbird

The URL for ‘Issues’ should be:
https://github.com/flathub/org.mozilla.Thunderbird/issues

For an example, see Kdenlive:
https://flathub.org/apps/details/org.kde.kdenlive

Thank you

**Comment by AdrianKoshka** [comment]
Same question as the one I had on #27

**Comment by ovari** [comment]
Does this work: https://github.com/flathub/org.mozilla.Thunderbird/pull/28?
