### ISSUE TITLE
Add ‘Donate’ button

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#27]
Add a ‘Donate’ button after the ‘Website’ button on:
https://flathub.org/apps/details/org.mozilla.Thunderbird

The URL for ‘Issues’ should be:
https://donate.mozilla.org/thunderbird/

For an example, see VLC:
https://flathub.org/apps/details/org.videolan.VLC

Thank you

**Comment by AdrianKoshka** [comment]
How would this be added? I would've thought it'd be done via appstream data, but I don't see an appstream data file in the VLC repo.

**Comment by ovari** [comment]
Does this work:
https://github.com/flathub/org.mozilla.Thunderbird/pull/28
