### ISSUE TITLE
Native notifications and file picker not working by default

### ISSUE THREAD

**Issue by ca-cl2** [flathub/org.mozilla.Thunderbird#290]
When I installed the Thunderbird flatpak on Debian 12 with libnotify 0.8.1, native notifications over DBus didn't work until I added back org.freedesktop.Notifications into the Talks section in Flatseal (PR #288).

**Comment by Erick555** [comment]
Do you have `mail.biff.use_system_alert` set to `false` or `true`?

https://github.com/flathub/org.mozilla.Thunderbird#new-mail-notifications

**Comment by ca-cl2** [comment]
It's set to true

**Comment by Erick555** [comment]
Hm, I can't reproduce then. Does xdg-desktop-portal work on your system, i.e. do you have all system files shown in file dialog?

**Comment by ca-cl2** [comment]
Interestingly, the file picker dialog doesn't work in Thunderbird, but it does work in other Flatpak apps.

**Comment by ca-cl2** [comment]
My DE is Sway (uses `xdg-desktop-portal-wlr`), and the file picker when it worked when I tried it out on Gnome with `xdg-desktop-portal-gnome`.

The file picker worked with the Bitwarden flatpak in Sway though.

**Comment by Erick555** [comment]
Do you have `xdg-desktop-portal-gtk` installed?

**Comment by ca-cl2** [comment]
Sorry for taking up your time, not having that installed was the whole problem... and turns out this was in the Arch Wiki the whole time.

Thank you for helping me anyway
