### ISSUE TITLE
Update to v102.11

### ISSUE THREAD

**Issue by StayPirate** [flathub/org.mozilla.Thunderbird#293]
A [new release](https://www.mozilla.org/en-US/security/advisories/mfsa2023-18/) is available. Could you please update?

**Comment by StayPirate** [comment]
@Erick555 do you have any script to prepare the commit for the next TB version bump for this repo? In this case, if you can share your process, the next time I can provide the PR instead of requesting you to do that as I did last time as well #291.

**Comment by Erick555** [comment]
Update script is [here](https://github.com/flathub/org.mozilla.Thunderbird/blob/master/update-thunderbird-version.sh).

**Comment by StayPirate** [comment]
I totally missed it, thanks for the explanation.
