### ISSUE TITLE
Multi-languages support

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.mozilla.Thunderbird#3]
Lingua PT-BR does not work

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by LeandroStanger** [comment]
@ramcq could help

**Comment by ramcq** [comment]
You need to fetch language packs (.xpi files) from https://download-origin.cdn.mozilla.net/pub/thunderbird during the build and include them with the Flatpak. Take a look at how Debian does it - http://http.debian.net/debian/pool/main/t/thunderbird/thunderbird_52.7.0-1.debian.tar.xz

**Comment by ramcq** [comment]
Right, at build time. That will mean you have all the files included in your Flatpak which will make it much larger, but you can fix this with a Locale extension. What you do is split the translations up again into subdirectories of /app/share/runtime/locale/<two letter ISO code>. Then you symlink back from wherever your app expects them to these path, then this folder will form your .Locale extension, and will be installed with just the languages are selected by the user / system / configuration of flatpak.

**Comment by AdrianKoshka** [comment]
How would I even begin to do this?

**Comment by AdrianKoshka** [comment]
Wouldn't it just be more efficient for people to install the language pack extension they need from the add-on store and not add complexity/size to the flatpak?

**Comment by nedrichards** [comment]
It would be simpler for the flatpak author, but much less simple for the user. But overall, I don't expect it would actually be that hard to put a few shell commands into a `post-install` script on the thunderbird build.

**Comment by AdrianKoshka** [comment]
> I don't expect it would actually be that hard to put a few shell commands into a post-install script on the thunderbird build.

Don't know if I was looking at the right thing, but it seems to do this for Thunderbird and lightning is over 600 lines of shell-script, and far from "simple". The files I'm looking at are:

- `create-lightning-l10n-tarball.sh`
- `create-thunderbird-l10n-tarball.sh`

**Comment by ovari** [comment]
Does this help:
assemble-flatpak-split-locales.patch
from:
https://github.com/flathub/org.libreoffice.LibreOffice
Full address:
https://github.com/flathub/org.libreoffice.LibreOffice/blob/master/assemble-flatpak-split-locales.patch

**Comment by AdrianKoshka** [comment]
@ovari So, if I understand correctly, that script does some symlink locale magic, and then fetches some language packs for libreoffice?

**Comment by ovari** [comment]
Looked like LibreOffice solved your situation. Not sure how exactly it works. Perhaps someone else can give better advise?

**Comment by ovari** [comment]
Flatpak manifest and patches to build Firefox
https://firefox-flatpak.mojefedora.cz/
https://github.com/xhorak/firefox-devedition-flatpak

**Comment by AdrianKoshka** [comment]
It probably does have a locale, BUT, you don't have the locale extension(s) that Firefox/Thunderbird has avilable.

**Comment by LeandroStanger** [comment]
How is the progress of the correction?

**Comment by AdrianKoshka** [comment]
I had forgotten about it, I'll post to the Thunderbird development mailing-list for help on this issue.

**Comment by LeandroStanger** [comment]
@AdrianKoshka  https://github.com/endlessm/firefox-flatpak/blob/master/org.mozilla.Firefox.json.in

**Comment by AdrianKoshka** [comment]
So, if I understand what you're showing me, I should just add the `.xpi` locales as an extra data in the manifest?

**Comment by LeandroStanger** [comment]
Yes

**Comment by AdrianKoshka** [comment]
cd51af61c7f21a92818f1cf9ca5cb40b878ce3fd should fix this issue, hopefully.

**Comment by nedrichards** [comment]
That won't quite do it. You also need the apply_extra script which runs on the extra data:

https://github.com/endlessm/firefox-flatpak/blob/master/apply_extra

to install those extensions (you probably don't want the preferences override that is used elsewhere)

Also, I'd strongly suggest moving to the more [modern extra-data format as seen in apps like Spotify](https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L168), it's much more readable and easy to update.

**Comment by AdrianKoshka** [comment]
Thanks, will look into and do.

**Comment by AdrianKoshka** [comment]
So would a script like this work?

```shell
THUNDERBIRD_DIR=$(pwd)/thunderbird

EXTENSIONS_DIR=${Thunderbird_DIR}/distribution/extensions
mkdir -p ${EXTENSIONS_DIR}
for addon in $(ls *.xpi); do
    mv "${addon}" "${EXTENSIONS_DIR}/$(get_extension_id ${addon}).xpi"
done

# Override preferences
PREFERENCES_DIR=${THUNDERBIRD_DIR}/browser/defaults/preferences
mkdir -p ${PREFERENCES_DIR}
ln -s /app/cache/mozilla/endless-default-prefs.js ${PREFERENCES_DIR}
```

**Comment by nedrichards** [comment]
I'd remove the 'override preferences' part - because that's not something you want. And you need something like:

```
# Retrieve the extension id for an addon from its install.rdf
# This function is taken from http://kb.mozillazine.org/Determine_extension_ID
get_extension_id() {
  unzip -qc $1 install.rdf | xmlstarlet sel \
    -N rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns# \
    -N em=http://www.mozilla.org/2004/em-rdf# \
    -t -v \
    "//rdf:Description[@about='urn:mozilla:install-manifest']/@em:id"
}
````
as well. I'll ping @ramcq here as well because he's looked at this before.

**Comment by AdrianKoshka** [comment]
So something like:

```
# Retrieve the extension id for an addon from its install.rdf
# This function is taken from http://kb.mozillazine.org/Determine_extension_ID
get_extension_id() {
  unzip -qc $1 install.rdf | xmlstarlet sel \
    -N rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns# \
    -N em=http://www.mozilla.org/2004/em-rdf# \
    -t -v \
    "//rdf:Description[@about='urn:mozilla:install-manifest']/@em:id"
}

THUNDERBIRD_DIR=$(pwd)/thunderbird

EXTENSIONS_DIR=${Thunderbird_DIR}/distribution/extensions
mkdir -p ${EXTENSIONS_DIR}
for addon in $(ls *.xpi); do
    mv "${addon}" "${EXTENSIONS_DIR}/$(get_extension_id ${addon}).xpi"
done
```

**Comment by AdrianKoshka** [comment]
Would this also mean we need to add `unzip` and `xmlstarlet` to the manifest?

**Comment by Pike** [comment]
I'd suggest to dig into how we build snaps for Firefox, https://dxr.mozilla.org/mozilla-central/source/taskcluster/docker/firefox-snap.

flatpack for Firefox seems to be work-in-progress, though: https://bugzilla.mozilla.org/show_bug.cgi?id=1278719

**Comment by AdrianKoshka** [comment]
Didn't really see anything useful there, can't exactly figure out how I'm supposed to apply this fix for `xml2-config` that I was pointed towards.

https://github.com/flathub/org.jamovi.jamovi/blob/5fddadce77adb54accd286a59ebb408a9cca5248/org.jamovi.jamovi.json#L277-L298

**Comment by LeandroStanger** [comment]
How is the progress of the correction?

**Comment by AdrianKoshka** [comment]
`libxlst` isn't building, so I haven't been able to progress much.

**Comment by LeandroStanger** [comment]
How is the progress of the correction?

**Comment by ovari** [comment]
[Bug 1441922 Generate multilocale Firefox flatpak](https://bugzilla.mozilla.org/show_bug.cgi?id=1441922)

**Comment by LeandroStanger** [comment]
How is the progress of the correction?

**Comment by LeandroStanger** [comment]
How is the progress of the correction?

**Comment by Lvaskz** [comment]
> How is the progress of the correction?

any progress?

**Comment by Erick555** [comment]
@Lvaskz something is cooking in https://github.com/flathub/org.mozilla.Thunderbird/pull/87 stay tuned :smile:

**Comment by Lvaskz** [comment]
thanks

**Comment by Erick555** [comment]
This is now fixed and will be published to flathub within couple of hours. For details see https://github.com/flathub/org.mozilla.Thunderbird#language-support
