### ISSUE TITLE
Add description, website, and topics

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#30]
On https://github.com/flathub/org.mozilla.Thunderbird
Replace:
_No description, website, or topics provided._
With:
```
:package: Flatpak manifest to build the Thunderbird application
https://flathub.org/apps/details/org.mozilla.Thunderbird
https://www.thunderbird.net/
```

Also add the following topics (alphabetical order):
`application` `container` `flathub` `flatpak` `mail` `mailclient` `thunderbird-mail`

Instructions: https://help.github.com/articles/classifying-your-repository-with-topics/

For examples of other applications:
https://github.com/topics/flathub

What do you think?

Thank you

**Comment by AdrianKoshka** [comment]
I don't have permission to change the description/topic/website part. I'd assume someone else might though.

**Comment by ovari** [comment]
Would they be seeing this issue?
