### ISSUE TITLE
[Fedora] Crash on the 102.13.0 version

### ISSUE THREAD

**Issue by proninyaroslav** [flathub/org.mozilla.Thunderbird#303]
**Fedora: 38**
**Thunderbird 102.13.0**

When I try to run the app I get the following errors:

```
Gtk-Message: 10:01:53.163: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:01:53.163: Failed to load module "pk-gtk-module"
Gtk-Message: 10:01:53.164: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:01:53.164: Failed to load module "pk-gtk-module"
```

I had to revert to a previous version:
```
flatpak update --commit=17bbaf3398a176ad210bf418c8b420586e26dd205d51f0754486a5c3bc86391a org.mozilla.Thunderbird
```

**Comment by hfiguiere** [comment]
These messages are annoying because each and everytime bug reporter think they are the bug, but they are just noise.

**Comment by proninyaroslav** [comment]
@hfiguiere 
Well, If you think that this is another joke and the app doesn't crash in the latest update, then I will close the issue.

**Comment by hfiguiere** [comment]
I'm not sure what you thought I wrote, but obviously it is far from what I actually wrote. But I guess the problem must not be important for you.

**Comment by proninyaroslav** [comment]
@hfiguiere 
I provide all the information that I had.

> But I guess the problem must not be important for you.

 Yes you are right. If you don't have a solution then I'll just stick with the old version or use the Fedora Flatpak package.

**Comment by Erick555** [comment]
@proninyaroslav app doesn't crash for me on Arch Linux, I test each update before publishing it.

You may try installing `org.mozilla.Thunderbird.Debug` and `org.freedesktop.Sdk//22.08` then do `flatpak run --devel org.mozilla.Thunderbird` and try to catch the crash with gdb.
