### ISSUE TITLE
Thunderbird 115.0 Supernova Release

### ISSUE THREAD

**Issue by msinfo32github** [flathub/org.mozilla.Thunderbird#307]
Thunderbird has released a new update, with a new UI and many more features. Is there an ETA for the Flatpak update?

**Comment by dcowan-london** [comment]
#306

**Comment by ghost** [comment]
this shouldn't be closed as completed, because it effectively isn't... completed

there is no 115 distribution on flatpak yet, from what I understand it's just coming soon:tm:

**Comment by 0b11001111** [comment]
It should as it is a duplicate by intend but does not even contribute any code ;)

**Comment by ghost** [comment]
> It should as it is a duplicate by intend but does not even contribute any code ;)

duplicate of which issue? and issues don't have to contribute code, they are used for tracking ;)
