### ISSUE TITLE
version 115?

### ISSUE THREAD

**Issue by xplosionmind** [flathub/org.mozilla.Thunderbird#308]
It seems that the work to package the groundbreaking version 115 has not started, not even in the beta branch… any ETA?

**Comment by LeMoonStar** [comment]
There has been some work on it in #306
Erick555 also explains why progress seems to be so slow at the moment in [this comment](https://github.com/flathub/org.mozilla.Thunderbird/pull/306#issuecomment-1632388273).

**Comment by xplosionmind** [comment]
Thanks @LeMoonStar ❤️
