### ISSUE TITLE
Create a README.rst

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#31]
Create a README.rst to display at https://github.com/flathub/org.mozilla.Thunderbird/

For example: https://github.com/karras/flatpak-claws-mail

Reference: https://gist.github.com/dupuy/1855764

**Comment by ovari** [comment]
Thanks for adding a README.

Sorry, we couldn't find how to provide a pull request for the following suggestions:
1. Change:
`https://addons.thunderbird.net/en-US/thunderbird/language-tools/`
to:
`https://addons.thunderbird.net/language-tools/`<br>
This will then open the languages tools in the locale of the person, eg:
https://addons.thunderbird.net/ar/thunderbird/language-tools/
https://addons.thunderbird.net/de/thunderbird/language-tools/
https://addons.thunderbird.net/en-US/thunderbird/language-tools/
https://addons.thunderbird.net/hu/thunderbird/language-tools/
https://addons.thunderbird.net/ja/thunderbird/language-tools/

1. Make the [#3](https://github.com/flathub/org.mozilla.Thunderbird/issues/3) and [#4](https://github.com/flathub/org.mozilla.Thunderbird/issues/4) links.

If you can point us to the direct file we can update using the GitHub Web Editor we can provide a pull request.

Thank you

**Comment by Erick555** [comment]
@ovari this is the file: https://github.com/flathub/org.mozilla.Thunderbird/blob/master/README.md 

Patches welcome :smile:
