### ISSUE TITLE
Add “Flatpak” to About dialog

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#38]
Please show that the version of Thunderbird is a “Flatpak”, via Thunderbird Menu Bar → Help → About Thunderbird. Thank you

Image below is from LibreOffice’s About dialog with green added showing “Flatpak version”.
![LibreOffice’s About dialog showing “Flatpak version”](https://user-images.githubusercontent.com/17465872/41803809-57ed0ba6-76d0-11e8-881a-b4c1d721e13f.png)

Recommend not having “version” to save translation just “Flatpak”, to be similar to Thunderbird Daily, i.e. Change “62.0a1 (2018-06-17) (64-bit)” to “52.8.0 Flatpak (64-bit)”.
![Thunderbird Daily About](https://user-images.githubusercontent.com/17465872/41817300-80004232-77db-11e8-8a33-e0e18b957c80.png)

**Comment by AdrianKoshka** [comment]
How do I do this..?

**Comment by ovari** [comment]
Would looking at the LO scripts work?

**Comment by AdrianKoshka** [comment]
I think it's done in their [build system](https://github.com/flathub/org.libreoffice.LibreOffice/blob/master/org.libreoffice.LibreOffice.json#L602), and not via patches.

> "./autogen.sh --prefix=/run/build/libreoffice/inst --with-distro=LibreOfficeFlatpak --disable-symbols $(if test \"$(uname -m)\" = aarch64; then printf %s --disable-pdfium; fi)"

**Comment by barthalion** [comment]
What is the use case?

**Comment by AdrianKoshka** [comment]
I was also going to ask this, I don't see why we need to distinguish the flatpak version of Thunderbird from non-flatpaked, but that's just my opinion.

**Comment by ovari** [comment]
A use case is when there are bug reports, specifying the source of the version can help reproduce, determine the cause and hence fix errors.

**Comment by AdrianKoshka** [comment]
> Does that mean code modifications need to happen in the Thunderbird core code?

Yes.

> A use case is when there are bug reports, specifying the source of the version can help reproduce, determine the cause and hence fix errors.

I suppose this might be a helpful use case.

**Comment by ovari** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1470730

**Comment by nedrichards** [comment]
@ovari this is exactly the sort of thing that can be added and improved when upstream has flatpak as an official distribution source and sees value in it. If that's true then everything else comes by default.

But more generally Flathub isn't a place for giant modifications and lots of patches. It's for distributing stable software from developers. Changes and requests should go on upstream, so thanks for filing a bug there.
