### ISSUE TITLE
Enigmail/GnuPG doesn't work

### ISSUE THREAD

**Issue by andrevmatos** [flathub/org.mozilla.Thunderbird#4]
Enigmail complains that `~/.gnupg` isn't writable, and that `gpg` isn't found in the path. Are there any flatpak interfaces to interact with the sockets directly (avoiding exposing private key, for example)? In my case, I use `~/.gnupg/trezor` as `GNUPGHOME`, can we support custom sockets/paths like that?

**Comment by TingPing** [comment]
In the long term it probably needs to be a portal so all of the decrypting/encrypting happens outside of the sandbox. Probably best discussing here: https://github.com/flatpak/xdg-desktop-portal/issues

**Comment by AdrianKoshka** [comment]
What would you suggest as an issue name?

**Comment by TingPing** [comment]
Portal for GPG encryption/decryption

Mention that you don't want to expose the entire gpg directory, keys and all, to applications for it.

**Comment by AdrianKoshka** [comment]
[Made an issue now](https://github.com/flatpak/xdg-desktop-portal/issues/178)

**Comment by treba123** [comment]
This is the by far most import issue to solve to make thunderbird on flatpak useful IMO. Many (security concerned) people I know use thunderbird mostly for Enigmail.

**Comment by AdrianKoshka** [comment]
I know an ssh agent portal was added recently (it works, probably isn't the most secure, but it works). Hopefully a gpg agent portal will be implemented.

**Comment by Erick555** [comment]
@andrevmatos @rmader does adding `flatpak run org.mozilla.Thunderbird --fileystem=~/.gnupg:rw` fix the problem for you?

**Comment by t2d** [comment]
The README says to run 
```
 flatpak override --filesystem=~/.gnupg org.mozilla.Thunderbird
```
I also had to run 
```
sudo flatpak override --filesystem=/run/user/1000/gnupg/ org.mozilla.Thunderbird
```
to give access to gpg-agent. Can you (dis-)confirm?

**Comment by AdrianKoshka** [comment]
I can't confirm, but this sounds like it should work. The worrying thign being, you're giving the sandbox access to your GPG keys directly.

**Comment by Erick555** [comment]
@t2d thx, I [updated README](https://github.com/flathub/org.mozilla.Thunderbird/pull/93/commits/ef21149f762c52bed3211216c53868b5503f94f8#diff-04c6e90faac2675aa89e2176d2eec7d8R40) and commit it alongside 68.2.1 soon.

**Comment by pjreed** [comment]
I've tried setting the overrides as described in the README, but it doesn't work for me.  The Key Management dialog lists all of my keys, but when I try to sign a message, I get a popup error that says:

> GnuPG cannot query your passphrase via pinentry.
> 
> This is a system setup or configuration error that prevents Enigmail from working properly and cannot be fixed automatically.
> 
> We strongly recommend that you consult our support web site at https://enigmail.net/faq.

Any ideas what might be wrong?  This is with Thunderbird 68.2.2, Enigmail 2.1.3, and gpg 2.2.4.

**Comment by Erick555** [comment]
@pjreed for unlocking keys protected by pin `pinentry` would need to be bundled in this flatpak.

**Comment by micahflee** [comment]
FYI I got a permission denied when I ran this:

```
$ flatpak override --filesystem=~/.gnupg org.mozilla.Thunderbird
error: Permission denied
```

But it worked with sudo:

```
$ sudo  flatpak override --filesystem=~/.gnupg org.mozilla.Thunderbird
```

**Comment by Erick555** [comment]
@micahflee yes, [it's noted in readme that it may require sudo](https://github.com/flathub/org.mozilla.Thunderbird#gpg-extension-support).

Specifically, this command require sudo when flatpak is installed system-wide in `/var/lib/flatpak`. If it's installed only for local user in `~/.local/share/flatpak` then it doesn't require sudo.

**Comment by Erick555** [comment]
@pjreed could you try installing from https://github.com/flathub/org.mozilla.Thunderbird/pull/97#issuecomment-559825926 and check if pinentry works?

**Comment by pjreed** [comment]
@Erick555 I've tried running that build, and I still get the same error about pinentry as before.  Here's what my overrides look like:
```bash
$ flatpak override --user --show org.mozilla.Thunderbird
[Context]
filesystems=xdg-run/gnupg:ro;~/.gnupg;
```
Should I need to adjust anything else?

**Comment by Erick555** [comment]
For some reason pinentry doesn't seem working:
```
$ flatpak run --command=sh --filesystem=~/.gnupg --filesystem=xdg-run/gnupg:ro org.mozilla.Thunderbird 
[📦 org.mozilla.Thunderbird ~]$ pinentry
OK Pleased to meet you
getpin
couldn't create prompt for gnupg passphrase: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
S ERROR gnome3.gcr_system_prompt_open 83886195 2: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
ERR 83886195 Configuration error <Pinentry>
```
You may check this yourself by running above flatpak command then executing `pinentry` in terminal and typing `getpin` then hitting enter.

I don't know what to do next.

**Comment by Erick555** [comment]
@pjreed I think i got it. You need additionally set:
` flatpak override --talk-name=org.gnome.keyring.SystemPrompter org.mozilla.Thunderbird`
After that executing pinentry & getpin shows PIN prompt for me. Please try if it works for you.

**Comment by pjreed** [comment]
That looks good, thanks!

**Comment by Erick555** [comment]
@pjreed I merged pinentry branch. TB update will be published in flathub in few hours, thx for testing.

**Comment by corecontingency** [comment]
First time trying flatpak'd Thunderbird. This bug seems to be happening for me. The Key Management dialog lists all of my keys, but when I try to sign a message, I get a popup error that says:

> 
> Your GnuPG installation is configured to use the console for pinentry. However, when using Enigmail you need a graphical version of pinentry.
> 
> This is a system setup or configuration error that prevents Enigmail from working properly and cannot be fixed automatically.
> 
> We strongly recommend that you consult our support web site at https://enigmail.net/faq.

Found this while testing my pull request #106 , but I am also having the same problem with the stable version. I even deleted my test build in case it was causing any interference.

As you can see, I am using the stable version from flathub installed with system:
```
[user@mycomputer ~]$ flatpak list
Thunderbird           org.mozilla.Thunderbird           68.6.0          stable          flathub        system
```

Here are my overrides:
```
[user@mycomputer ~]$ flatpak override --show org.mozilla.Thunderbird
[Context]
filesystems=xdg-run/gnupg:ro;~/.gnupg;/run/user/1000/gnupg/;

[Session Bus Policy]
org.gnome.keyring.SystemPrompter=talk
```


```
[michael@linuxlaptop ~]$ flatpak run --command=sh org.mozilla.Thunderbird
[📦 org.mozilla.Thunderbird ~]$ pinentry
OK Pleased to meet you
getpin
D ihbjbobnkn
OK
```
`pinentry` works fine, it opens a popup and I can type whatever. As you can see, it gets echoed properly.

Using Arch Linux with GNOME on Xorg. Also have a btrfs root filesystem with subvolumes.

Can anyone confirm this behavior? Any ideas?

**Comment by rmader** [comment]
Do you have a btrfs subvolume mounted as root? Because apparently there are other programs dealing with flatpak that get confused by that, thinking it must be within a flatpak sandbox and therefore "translate" the path. See e.g. https://gitlab.gnome.org/GNOME/sysprof/issues/34

**Comment by corecontingency** [comment]
Yes. Here is my [fstab](https://paste.ubuntu.com/p/XVpR38cHZy/), and here is my [root btrfs subvolume (subvolid=5)](https://paste.ubuntu.com/p/8nmpWw3NDK/).

**Comment by Erick555** [comment]
openpgp should work be default in TB 78.3.1 (but not enigmail).

**Comment by fourstepper** [comment]
I also have my root on a btrfs subvolume, running flatpak run --command=sh org.mozilla.Thunderbird and gpg --list-keys works fine and gives me my key on the CLI, but in the GUI, I don't see any keys.

I am not sure if the keys have to be imported somehow or discovered...

![image](https://user-images.githubusercontent.com/49439044/108117717-31a0ec80-7095-11eb-94e7-961f7ed87c44.png)

**Comment by Erick555** [comment]
@fourstepper thunderbird doesn't use gnupg by default. If you had enigmail installed then there should be some migration toll otherwise you have to import your keys manually.

https://wiki.mozilla.org/Thunderbird:OpenPGP:Migration-From-Enigmail

https://wiki.mozilla.org/Thunderbird:OpenPGP:Smartcards
