### ISSUE TITLE
Not isolated from the RPM version

### ISSUE THREAD

**Issue by fbruetting** [flathub/org.mozilla.Thunderbird#50]
Everytime I try to open the flatpak version of Thunderbird, it opens my RPM version. With the newest update even the TB icon degraded from the v60 icon to the v52 icon… 😳

**Comment by AdrianKoshka** [comment]
> Everytime I try to open the flatpak version of Thunderbird, it opens my RPM version.

Perhaps uninstall the RPM version? Unless there's some functionality you absolutely need from it, I don't see why you would have both installed.

> even the TB icon degraded from the v60 icon to the v52 icon…

Should have happened if you did updates, I downgraded back to v52 because users were having issues with v60.

**Comment by fbruetting** [comment]
Fatpak applications should be isolated in general, so that you can use different versions in parallel. This is currently not possible.

I’d like to test the Flatpak version first, before relying on it, especially because of my smartcard reader.

**Comment by AdrianKoshka** [comment]
> Fatpak applications should be isolated in general, so that you can use different versions in parallel. This is currently not possible.

Wouldn't say it's not possible, just that flathub uses only one branch.

> I’d like to test the Flatpak version first, before relying on it, especially because of my smartcard reader.

Ah, understandable. I guess if you want a sure-fire way of running the flatpak, you could run `flatpak run org.mozilla.Thunderbird`.

**Comment by fbruetting** [comment]
I know, but when TB-RPM runs, that command doesn’t do anything on my Fedora 28 system except for quitting again.

**Comment by AdrianKoshka** [comment]
Are you saying when you run `flatpak run org.mozilla.Thunderbird` it only crashes?

**Comment by fbruetting** [comment]
It never even starts, but I think I just tried it while TB-RPM was running.

**Comment by AdrianKoshka** [comment]
Then close it before you try to launch it...

**Comment by fbruetting** [comment]
Yeah, that’s the point. Flatpak is here to absolutely separate all instances. You seem to have completely circumvented the bubblewrap sandbox. That’s not good.

**Comment by fbruetting** [comment]
Hm ok, then I misunderstood that… sorry then.
