### ISSUE TITLE
opensc support

### ISSUE THREAD

**Issue by fbruetting** [flathub/org.mozilla.Thunderbird#51]
I need to access `opensc` which resides in /usr/lib64/ on my Fedora 28 system. But when I go into “manage security devices”, I solely see `ld-linux-x86-64.so.2` in that directory, though there is much more content in it. Seems like a Flatpak sandbox restriction?

**Comment by Erick555** [comment]
Yes, flatpak don't use host libraries.

**Comment by fbruetting** [comment]
Can this be made accessible on for example `/var/run/host` (or whatever the right spot would be)?

**Comment by fbruetting** [comment]
Or would that new `flatpak-common` help? See the section “Future work” of this article:

https://blog.fishsoup.net/2018/12/04/flatpaks-in-fedora-now-live/

**Comment by barthalion** [comment]
It's unrelated to Flathub.

**Comment by Erick555** [comment]
Could anyone test if https://github.com/flathub/org.mozilla.Thunderbird/pull/70#issuecomment-526823084 works?

**Comment by fbruetting** [comment]
I will check this week. 😀️

**Comment by fbruetting** [comment]
Sorry for the delay, I just tried to install but got this error message with a SIGIOT return code:

```
> flatpak install https://dl.flathub.org/build-repo/7884/org.mozilla.Thunderbird.flatpakref
**
flatpak:ERROR:app/flatpak-main.c:508:flatpak_run: assertion failed: (success || error)
Aborted (Speicherabzug geschrieben)
```

Any suggestions?

**Comment by Erick555** [comment]
@fbruetting I think the test build dissapered from server. I'll do a fresh one however you won't be able to test smartcard functionality without flatpak 1.3.2+. On ubuntu based systems you can try latest from [ppa](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak).
