### ISSUE TITLE
Update the Thunderbird icon on flathub.org

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#52]
Please update the Thunderbird icon at:
https://flathub.org/apps/details/org.mozilla.Thunderbird
https://flathub.org/repo/appstream/x86_64/icons/128x128/org.mozilla.Thunderbird.png
![image](https://user-images.githubusercontent.com/17465872/46250812-42ca0e00-c486-11e8-9bf5-5952cfb24717.png)

Perhaps these sources can help:
https://demo.identihub.co/thunderbird#/
https://github.com/mozfr/www/blob/master/source/img/thunderbird_32px.png
https://github.com/mozfr/www/blob/master/source/img/thunderbird_48px.png
https://github.com/mozfr/www/blob/master/source/img/thunderbird_60px.png
https://demo.identihub.co/assets/Thunderbird_ICONS_1.svg

![268x268](https://user-images.githubusercontent.com/17465872/46250849-0a76ff80-c487-11e8-97c1-927a10b63d9d.png)

How can the image below:
![128x128](https://user-images.githubusercontent.com/17465872/46250851-0c40c300-c487-11e8-91af-4dd6bb55e91f.png)
replace:
https://flathub.org/repo/appstream/x86_64/icons/128x128/org.mozilla.Thunderbird.png
?

Thank you

**Comment by Erick555** [comment]
Perhaps the icon isn't updated because flathub has older version of Thunderbird because of https://github.com/flathub/org.mozilla.Thunderbird/issues/46

**Comment by Erick555** [comment]
New icons is correctly shown on https://flathub.org/apps/details/org.mozilla.Thunderbird
