### ISSUE TITLE
Thunderbird still installs cleanly and appears on flathub.org even though it is EOL

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.mozilla.Thunderbird#57]
Thunderbird has been marked as EOL here https://github.com/flathub/org.mozilla.Thunderbird/blob/master/flathub.json .

But when I search and install the package on the CLI I don't get any warning.

Also it still appears on the Flathub website https://flathub.org/apps/details/org.mozilla.Thunderbird

**Comment by jgarciao** [comment]
The website doesn't automatically remove the apps (yet). There is a manual process involving removing the info from the database (alex knows)

Regardless of that, something else might be missing because flatpak remote-info doesn't show Thunderbird as EOL like other apps (see the difference below)
```
flatpak --system remote-info flathub org.mozilla.Thunderbird

Thunderbird - Email, RSS and newsgroup client with integrated spam filter

        ID: org.mozilla.Thunderbird
       Ref: app/org.mozilla.Thunderbird/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 52.9.1
   License: MPL-2.0
Collection: org.flathub.Stable
  Download: 62,3 MB
 Installed: 135,6 MB
   Runtime: org.gnome.Platform/x86_64/3.28

       Sdk: org.gnome.Sdk/x86_64/3.28
    Commit: dc227da36671364bdbaaa4fb56006f42dd1aa86d7d347ea2e4b2fd96a49574b3
    Parent: 2557d76300a4265d5c64120815f34a141a6e5cbb5aaab0e457f75bd0f0a913f4
   Subject: Mark thunderbird end-of-life due to lack of maintainer (ca3b4b7b)
      Date: 2019-02-20 10:43:21 +0000
```

In contrast (notice the extra "End-of-life" line):
```
 flatpak --system remote-info flathub org.gnome.Epiphany
         ID: org.gnome.Epiphany
        Ref: app/org.gnome.Epiphany/x86_64/stable
       Arch: x86_64
     Branch: stable
 Collection: org.flathub.Stable
   Download: 3,4 MB
  Installed: 5,1 MB
    Runtime: org.gnome.Platform/x86_64/3.28

        Sdk: org.gnome.Sdk/x86_64/3.28
     Commit: 763fce60cfc7096c2de96293b8ac0e1dde8f0dbd3bcab45e19d28fbb20c2af6d
     Parent: 767ecdc73284fec20da8e2f0c7ba2de14e62e12c60bd08d3b464c79ea3387647
End-of-life: Epiphany is temporarily no longer offered via Flathub due to lack of security support for the Flatpak runtimes.
    Subject: Mark this repo as EOL (590097a6)
       Date: 2018-08-06 17:16:01 +0000

```

**Comment by tilosp** [comment]
cc @alexlarsson

**Comment by TingPing** [comment]
It has to be manually removed.

https://github.com/flathub/linux-store-frontend/issues/126

**Comment by ahayzen** [comment]
Yup, for the frontend it's currently a manual process (flathub.org) but it seems as Jorge pointed out even the ostree repo hasn't been updated as the flatpak CLI doesn't post the normal message. Is that a manual process as well or did something go wrong with the build ?

**Comment by TingPing** [comment]
Seems to have built fine: https://flathub.org/builds/#/builders/32/builds/125

**Comment by tilosp** [comment]
@TingPing i think the new infra does not support eol properly
The build was successful but it shows `{"build":117,"endoflife":null}` here https://flathub.org/builds/#/builders/32/builds/125/steps/11/logs/stdio
and `flatpak remote-info flathub org.mozilla.Thunderbird` also dosn't show it

**Comment by x80486** [comment]
Looks like Fedora started shipping Thunderbird (as well as Firefox):

```shell
[x80486@uplink ~]$ flatpak remote-ls fedora | grep mozilla
Firefox - Browse the Web                 org.mozilla.Firefox         stable
Thunderbird - Send and Receive Email     org.mozilla.Thunderbird     stable
```

Is it possible to somehow reference/store/host those in Flathub as well?

> The remote can be added as: `flatpak remote-add --if-not-exists fedora oci+https://registry.fedoraproject.org`

**Comment by Erick555** [comment]
No, fedora is repackaging them from rpm packages and they need fedora runtime. Note that opening attachments with external apps doesn't work: https://bugzilla.redhat.com/show_bug.cgi?id=1698666

**Comment by jgarciao** [comment]
@x80486 If you want the website to show applications from other flatpak
repositories (like fedora or elementary) please open a new issue asking for
the feature, but I promise nothing in the near future...

**Comment by Erick555** [comment]
@x80486 [I made successful build latest TB on flathub](https://github.com/flathub/org.mozilla.Thunderbird/pull/58#issuecomment-487406072). You may test if you want.

**Comment by barthalion** [comment]
> Is it possible to somehow reference/store/host those in Flathub as well?

Flathub is Flathub, Fedora does their own thing so they should rather deploy the web frontend themselves.

**Comment by Erick555** [comment]
Installing TB shows:
`Info: org.mozilla.Thunderbird is end-of-life, with reason: Currently no maintainer for the flathub package.`. 

`flatpak remote-info flathub org.mozilla.Thunderbird` shows:
`End-of-life: Currently no maintainer for the flathub package.`

https://flathub.org/apps/details/org.mozilla.Thunderbird shows nothing.

I think we can conclude that it's marked as EOL correctly.
