### ISSUE TITLE
Move `https://github.com/flathub/org.mozilla.Thunderbird` to `https://github.com/flathub/net.thunderbird.Thunderbird`

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#59]
Should this be renamed/moved from
`https://github.com/flathub/org.mozilla.Thunderbird`
to
`https://github.com/flathub/net.thunderbird.Thunderbird`
?

Thank you

**Comment by ovari** [comment]
https://github.com/flathub/org.mozilla.Thunderbird/issues/1#issuecomment-525944602

**Comment by Erick555** [comment]
I don't have opinion. I won't rename anything myself.

**Comment by TingPing** [comment]
Step one is get the appdata/desktop file upstream, then *they* will decide the correct app-id and we can match what they want.

**Comment by Erick555** [comment]
I re-open as something upstream to consider after maintenance takeover. They indeed have [appdata with net.thunderbird.Thunderbird name](https://hg.mozilla.org/comm-central/file/tip/mail/branding/thunderbird/net.thunderbird.Thunderbird.appdata.xml) but I don't know if it's used for anything (it doesn't pass `appstream-util validate` anyway.

**Comment by Erick555** [comment]
Apparently the correct appid should be `org.mozilla.thunderbird` otherwise it causes issues with dbus ownership: https://github.com/flathub/org.mozilla.Thunderbird/issues/109

**Comment by Erick555** [comment]
Flatpak is now managed by Thunderbird team. Closing
