### ISSUE TITLE
Segfault at startup

### ISSUE THREAD

**Issue by memnoth** [flathub/org.mozilla.Thunderbird#60]
Since the commit, https://github.com/flathub/org.mozilla.Thunderbird/commit/a9e1843e20ced796516b8e6872bd4ce8f777bba9, it doesn't allow to access host cache and as the commit said, users need to manually restore it.

However, neither copying cache files under ``~/.thunderbird`` directory into ``~/.var/app/org.mozilla.Thunderbird/`` nor ``~/.var/app/org.mozilla.Thunderbird/cache/thunderbird`` work on me.

Anyone succeeded in restoration?

Edit: ``~/.cache/thunderbird`` has nothing at all by the way.

**Comment by Erick555** [comment]
@memnoth That commit referred to copying config files from `~/.thunderbird` to` ~/.var/app/org.mozilla.Thunderbird/.thunderbird`. Is that not working for you?

I don't see a reason for copying cache files from `~/.cache/thunderbird`. Flatpak app should create its own cache in `~/.var/app/org.mozilla.Thunderbird/cache/thunderbird` automatically.

**Comment by memnoth** [comment]
Sorry for confusing you. I meant copying config files from the path to the new one doesn't work on me at all. When I started the program after done with the update, All my config, for e.g, email list gone. So I copied the configs manually to the new path as you mentioned and then, seg fault was up.

I will reinstall it and then will try again.

**Comment by memnoth** [comment]
I guess it might be another problem... No matter copying old configs or add new accounts segfault came up.  Does it only happen to me?

**Comment by Erick555** [comment]
Could you try with `-safe-mode`? `flatpak run org.mozilla.Thunderbird -safe-mode`.

**Comment by Erick555** [comment]
I switched back to bundled sqlite in [latest update](https://github.com/flathub/org.mozilla.Thunderbird/commit/642ee39a554f2eb4b6042932809aa81e00f8ad2f). You may try if it helped you.

**Comment by memnoth** [comment]
Segfault still comes up with the latest update.

**Comment by Erick555** [comment]
Could you try renaming global-messages-db.sqlite to global-messages-db.sqlite.old inside `.thunderbird/<profile_folder>/`?

**Comment by Erick555** [comment]
You may also try to remove `~/.var/app/org.mozilla.Thunderbird/.thunderbird` and copy old `~/.thunderbird` there if you still have it.

**Comment by Erick555** [comment]
@memnoth this may be fixed by https://github.com/flathub/org.mozilla.Thunderbird/commit/eb0c7cf5b9af24de7d2201c0e671e6e9fbd5b7fd which will be released by few hours in flathub. I you could still reprodece the crash after that feel free to re-open this ticket.
