### ISSUE TITLE
Thunderbird can't be found on flathub.org

### ISSUE THREAD

**Issue by Zlopez** [flathub/org.mozilla.Thunderbird#62]
Hi,

I noticed that searching for Thunderbird on flathub.org finds nothing. This is probably some issue with metadata
See https://flathub.org/apps/search/thunderbird

**Comment by Erick555** [comment]
This is [intentional](https://github.com/flathub/org.mozilla.Thunderbird/pull/56). You should see:

> Info: org.mozilla.Thunderbird is end-of-life, with reason: Currently no maintainer for the flathub package

message while installing TB.

**Comment by Zlopez** [comment]
Sorry for bothering you than, I didn't realized that Thunderbird on Flathub is now EOL.

**Comment by Erick555** [comment]
@Zlopez I recently updated it to latest TB release + gnome runtime version. If it will work ok for users then there is a chance to resurrect it from dead so any feedback from testing is welcome.

**Comment by ovari** [comment]
[Thunderbird 68.1.0](https://www.thunderbird.net/thunderbird/all/) is now available. [Click here for the Thunderbird Release Notes](https://www.thunderbird.net/thunderbird/68.1.0/releasenotes/).

@Erick555:
1. Can you please resurrect Thunderbird from the dead?
1. Can you please provide the link and/or instructions to test the TB 68.1.0 version?
1. Should this issue be re-opened?

Thank you

**Comment by Erick555** [comment]
@ovari I can't build TB with current runtime due to some clang error, see https://github.com/flathub/org.mozilla.Thunderbird/pull/73
I plan to try with new freedesktop 19.08 runtime but first I need `org.freedesktop.Sdk.Extension.node10` to support it.

**Comment by ovari** [comment]
@Erick555 Sorry to hear about the error. Does you know the when  [org.freedesktop.Sdk.Extension.node10](https://github.com/flathub/org.freedesktop.Sdk.Extension.node10) will be supported? Thank you once again

**Comment by Erick555** [comment]
I don't know but I hope it will be in couple of days.

**Comment by ovari** [comment]
> Okay I pushed it, let's see how the [build](https://flathub.org/builds/#/builders/32/builds/8241) goes.
https://github.com/flathub/org.freedesktop.Sdk.Extension.node10/issues/3#issuecomment-531615555

> Looks like it's good to go! (Still uploading, but the build was a success.)
https://github.com/flathub/org.freedesktop.Sdk.Extension.node10/issues/3#issuecomment-531621490

@Erick555 can you now try to build [Thunderbird 68.1.0](https://www.thunderbird.net/) for Flatpak? Thank you
