### ISSUE TITLE
not on flathub 

### ISSUE THREAD

**Issue by damianatorrpm** [flathub/org.mozilla.Thunderbird#68]
is this not on flathub anymore? only empty results

**Comment by Erick555** [comment]
For now this app is [EOL](https://github.com/flathub/org.mozilla.Thunderbird/blob/master/flathub.json#L2). You can install it only through cli: `flatpak install flathub org.mozilla.Thunderbird`.

**Comment by damianatorrpm** [comment]
Oh, I see so if one was to step up maintaining it, it would be re-added I guess?
Is there a list of applications for flathub that rea EOL or respectively not "on" flathub?

**Comment by Erick555** [comment]
Yes, after I update it to 68.x which will have portal support I'll ask to re-add it. I don't think there is a list of EOL apps.

**Comment by damianatorrpm** [comment]
Thanks!
