### ISSUE TITLE
Enable --socket=wayland

### ISSUE THREAD

**Issue by p1u3o** [flathub/org.mozilla.Thunderbird#75]
The manifest should enable --socket=wayland for Wayland support

Thunderbird will still use X.org by default, but this allows the experimental Wayland support to be enabled.

**Comment by Erick555** [comment]
@p1u3o did you tested running this app on wayland with `--socket=wayland --env=MOZ_ENABLE_WAYLAND=1`?

**Comment by p1u3o** [comment]
I tested running it with --socket=wayland --env=GDK_BACKEND=wayland

**Comment by Erick555** [comment]
I added wayland socket and some documentation in https://github.com/flathub/org.mozilla.Thunderbird/pull/76 . Thx for reporting.

**Comment by antistress** [comment]
Sorry but I doubt that this bug is fixed.
Although /var/lib/flatpak/exports/share/applications/org.mozilla.Thunderbird.desktop says `--socket=wayland` thunderbird still run with windowProtoco = x11as about:support says and as xlsclients confirms.
Therefore I think this bug should be reopened.
Thanks

**Comment by Erick555** [comment]
@antistress wayland support in firefox/thunderbird is still experimental, you need to pass `--env=MOZ_ENABLE_WAYLAND=1` to enable it. it won't be enabled by default until upstream does it.

**Comment by antistress** [comment]
Indeed, sorry for the noise.
Thanks for pointing this and for your work :)

**Comment by antistress** [comment]
> @antistress wayland support in firefox/thunderbird is still experimental, you need to pass `--env=MOZ_ENABLE_WAYLAND=1` to enable it. it won't be enabled by default until upstream does it.
> 
> This is written in [README](https://github.com/flathub/org.mozilla.Thunderbird#wayland) already.

Sorry,  it's a bot off topic, but maybe you would like to mention in README that, under Wayland, user could experiment https://bugzilla.mozilla.org/show_bug.cgi?id=1601676 and https://github.com/flatpak/flatpak/issues/2861

**Comment by antistress** [comment]
Hi, with Debian testing Gnome 42.2 and Thunderbird 91.10.0 flatpak from Flathub, I still have to :
`$ flatpak override --user --env=MOZ_ENABLE_WAYLAND=1 --socket=wayland org.mozilla.Thunderbird`
to get Thunderbird run under Wayland without XWayland.
Any plan to get it running natively under Wayland by default ?

**Comment by Erick555** [comment]
Flatpak only packages what upstream provides and upstream doesn't enable wayland by default. You need to wait until they do.

**Comment by antistress** [comment]
Thanks

Here is related meta bug for those who wander what's current state 
https://bugzilla.mozilla.org/show_bug.cgi?id=1542587
