### ISSUE TITLE
Change listing from `org.mozilla.Thunderbird` to `Thunderbird (Flathub)` or `Thunderbird`

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#77]
When searching for `thunderbird` in Linux Mint's Software Manager, please change the listing which shows from `org.mozilla.Thunderbird` to `Thunderbird (Flathub)`. LibreOffice's Flathub listing is shown as `LibreOffice (Flathub)`. Please see images below.

![Change listing from `org.mozilla.Thunderbird` to `Thunderbird (Flathub)`](https://user-images.githubusercontent.com/17465872/65080497-cb69f300-d9e4-11e9-855b-5ef88b43a047.png)

![LibreOffice (Flathub)](https://user-images.githubusercontent.com/17465872/65080535-df155980-d9e4-11e9-8a05-cb4045b0d343.png)

What do you think?

Thank you

**Comment by TingPing** [comment]
Nothing should append `(Flathub)`. I suspect the current name is just a bug in Mint's Software Manager but that needs to be confirmed.

**Comment by ovari** [comment]
Should the name be changed from `org.mozilla.Thunderbird` to `Thunderbird`?

**Comment by ovari** [comment]
Image shows `GNU Image Manipulation Program`, without the ` (Flathub)`, which is from Flathub.

Linux Mint seems to only append the ` (Flathub)` if the name is not unique.

![image](https://user-images.githubusercontent.com/17465872/65105831-93c96e00-da19-11e9-8574-c4f22508926e.png)

**Comment by TingPing** [comment]
The name *is* Thunderbird. That is why I assume its a Mint bug.

**Comment by ovari** [comment]
Perhaps all the data had not populated. Now it shows correctly. Sorry for the noise.

![Thunderbird (Flathub)](https://user-images.githubusercontent.com/17465872/65192090-5a483f80-dab9-11e9-9467-3885dd99f323.png)
