### ISSUE TITLE
notifications aren't clickable on KDE

### ISSUE THREAD

**Issue by mjgritli** [flathub/org.mozilla.Thunderbird#79]
Dear Mozilla/Thunderbird team ...

I've been using Linux for more than 12 years now ... used Unity then adapted to Gnome and finally I'm a fan of KDE.
on KDE, Thunderbird sends notifications for 
![Screenshot_20190918_155941](https://user-images.githubusercontent.com/10092152/65155789-28d66200-da2e-11e9-8adf-f6d4b7bfeb4a.png)
new emails, however, they aren't clickable, so it doesn't open Thunderbird and shows you the email, it only has a close button.
please fix this problem, its frustrating, and must be function 
Kind regards
Mohammed Gritli

**Comment by Erick555** [comment]
First of all flathub app isn't affiliated with with Mozilla/Thunderbird.

Secondly I'm not sure if I understand you correctly - when you run TB flatpak on gnome clicking on notifications work but on kde it doesn't? Or did it worked with TB from distro repos? Keep in mind that ubuntu provide some special extension for [notifications](https://github.com/flathub/org.mozilla.Thunderbird/issues/10) in TB. You can request for adding something like it in upstream TB [here](https://bugzilla.mozilla.org/buglist.cgi?product=Thunderbird&bug_status=__open__) if nobody asked for it already

**Comment by Erick555** [comment]
For now  can confirm that clicking on notifications doesn't work when using TB from my distro repos on KDE.

**Comment by Erick555** [comment]
Closing as this is upstream issue, non actionable here.

**Comment by mjgritli** [comment]
ok,
I'm surprized no one pointed that out, I like TB, and hope this issue is fixed in the very next release.
Good luck
Kind Regards

**Comment by ovari** [comment]
Can you please cross-reference the bug listing here from Thunderbird Bugzilla?
https://bugzilla.mozilla.org/describecomponents.cgi?product=thunderbird

Thank you

**Comment by Erick555** [comment]
Related upstream tickets are here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1491691
https://bugzilla.mozilla.org/show_bug.cgi?id=1583071
Workaround is setting `mail.biff.use_system_alert` to `false` which makes notifications non-system native and uglier but clickable.

**Comment by Erick555** [comment]
I mentioned workaround in readme: https://github.com/flathub/org.mozilla.Thunderbird#new-mail-notifications
