### ISSUE TITLE
Errors installing via Mint store

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#80]
Add `runtime/org.freedesktop.Platform/x86_64/19.08` to the dependency list and automatically install if required.

What do you think?

Thank you

![image](https://user-images.githubusercontent.com/17465872/65192605-fde61f80-daba-11e9-9b5b-6f6fd17577d4.png)

![image](https://user-images.githubusercontent.com/17465872/65192490-94fea780-daba-11e9-865d-817cba55ec6e.png)

**Comment by TingPing** [comment]
This sounds like another bug of the Mint store.

**Comment by ovari** [comment]
@clefebvre can you please reproduce and fix this bug with Linux Mint 19.2 Cinnamon 64-bit? Thank you

**Comment by TingPing** [comment]
I believe `flatpak` 1.2.5 is needed to avoid this error. Its not actually a fatal error and the application should run fine though.

**Comment by Erick555** [comment]
I think this is bug in mint store and will occur with any app using freedesktop 19.08. It's unrelated to TB.

**Comment by ovari** [comment]
Seems to be an `openh264 flatpak` bug.
https://github.com/linuxmint/mintcommon/pull/36#issuecomment-533920021

Could you please advise the link to the `openh264 flatpak` repository?

Thank you

**Comment by Erick555** [comment]
@ovari That comment was misleading and [I clarified it here](https://github.com/linuxmint/mintcommon/pull/36#issuecomment-534071424). Anyway this was mint bug which was fixed by https://github.com/linuxmint/mintcommon/commit/ded9e9e733e42a26b7441b6c4cf3e86ed8e1efe7
