### ISSUE TITLE
Crashes every time after one succesfull run.

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/org.mozilla.Thunderbird#82]
I successfully run it for the 1st time and tried to add an account then it crashed immediately. Every other time it crashes with messages:
```
$ flatpak run -v org.mozilla.Thunderbird
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/thanos/.local/share/flatpak
F: Opening user flatpak installation at path /home/thanos/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/thanos/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 3829295092
F: Allocated instance id 3710036538
F: Add defaults in dir /org/mozilla/Thunderbird/
F: Add locks in dir /org/mozilla/Thunderbird/
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/thanos/.config/pulse/client.conf': Error opening file /home/thanos/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 38 xdg-dbus-proxy --args=40'
F: Running 'bwrap --args 38 thunderbird'
Gtk-Message: 20:52:56.042: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:52:56.042: Failed to load module "canberra-gtk-module"
```

EDIT: I thought it could get fixed with overrides but I was wrong. I cannot fix it.

My distro is Fedora 31.

**Comment by Erick555** [comment]
Please install `org.freedesktop.Sdk//19.08` and `org.mozilla.Thunderbird.Debug` then run:
`flatpak run --command=sh --devel org.mozilla.Thunderbird`
`gdb /app/lib/thunderbird/thunderbird`

It's likely you would have to report it [upstream](https://bugzilla.mozilla.org/buglist.cgi?order=Importance&resolution=---&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&query_format=advanced&product=Thunderbird).

**Comment by ThanosApostolou** [comment]
Here's the output of these commands:
https://pastebin.com/6FFuz7TL

I'm not familiar with gdb, do I need to run anything else other than just `run` in the gdb shell?

**Comment by Erick555** [comment]
Thx, you may download also `org.freedesktop.Sdk.Debug` (it's quite big, about 2GB) to get better output however it seem related to gnome shell and URI protocol registration:
```
bool nsGNOMEShellService::checkDefault(const char *const *aProtocols,
                                       unsigned int aLength) {
  nsCOMPtr<nsIGIOService> giovfs = do_GetService(NS_GIOSERVICE_CONTRACTID);

  nsAutoCString handler;
  nsresult rv;

  for (unsigned int i = 0; i < aLength; ++i) {
    if (giovfs) {
      handler.Truncate();
      nsCOMPtr<nsIHandlerApp> handlerApp;
      rv = giovfs->GetAppForURIScheme(nsDependentCString(aProtocols[i]),
                                      getter_AddRefs(handlerApp));
      if (NS_FAILED(rv) || !handlerApp) {
        return false;
      }
      nsCOMPtr<nsIGIOMimeApp> app = do_QueryInterface(handlerApp, &rv);
      if (NS_FAILED(rv) || !app) {
        return false;
      }
      rv = app->GetCommand(handler);
      if (NS_SUCCEEDED(rv) && !CheckHandlerMatchesAppName(handler)) {
        return false;
      }
    }
  }

  return true;
}
```
Can you confirm that it happens under gnome session? Also is it wayland or x11?

Maybe you can try `flatpak run --socket=system-bus org.mozilla.Thunderbird`.

**Comment by ThanosApostolou** [comment]
I can confirm that it happens on both Gnome Wayland and X11 as well as KDE Plasma sessions.

`flatpak run --socket=system-bus org.mozilla.Thunderbird` doesn't make a difference.

I will try to install `org.freedesktop.Sdk.Debug//19.04` later and post again the gdb output.

**Comment by ThanosApostolou** [comment]
Yep. Here's is screenshot from kde session.
![Screenshot_20191001_181701](https://user-images.githubusercontent.com/21288843/65975855-ed00bb00-e477-11e9-8fb5-1381ec43aa1b.png)

I guess it somehow detects Gnome is installed or from some service running. I see the code you posted is relevant to gvfs and I still have many gnome apps installed and gvfs, goa, etc. running.

**Comment by Erick555** [comment]
Maybe you can try `flatpak run --filesystem=xdg-run/gvfs --talk-name=org.gtk.vfs --talk-name=org.gtk.vfs.* org.mozilla.Thunderbird`.

Also you can install `org.gnome.Platform//3.34` then `flatpak run --runtime=org.gnome.Platform//3.34 org.mozilla.Thunderbird`.

**Comment by ThanosApostolou** [comment]
These didn't work but I hadn't noticed that you pushed changes yesterday, so I did a `flatpak update` and problem solved. Feel free to close this.

**Comment by Erick555** [comment]
Ok, thx for info.
