### ISSUE TITLE
Last Update broke Calendar

### ISSUE THREAD

**Issue by go-ten** [flathub/org.mozilla.Thunderbird#86]
Hello,

The last update (07.10.2019) broke the Lightning calendar.
For Info, I use thr add ons Lightning (from the market), Provider for Exchange Activesync and TBSync.

Any Ideas ?

**Comment by Erick555** [comment]
Yes, [this was intentional](https://github.com/flathub/org.mozilla.Thunderbird#calendar-extension) as it was troublesome for non-english users. Please re-download calendar from extension store.

**Comment by Erick555** [comment]
Ok, I will bundle calendar again

**Comment by Erick555** [comment]
Will be fixed once https://github.com/flathub/org.mozilla.Thunderbird/commit/4e2e8db9dd328b2a29b61372967d890323138d75 is build and published in about few hours

**Comment by Erick555** [comment]
@go-ten update is on flathub, it should work as before, sorry for the trouble.

**Comment by go-ten** [comment]
Hello,
No worries for the trouble. It works now !!
Thanks
