### ISSUE TITLE
Localize Calendar extension

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#88]
> Note that Calendar extension is not localized and available only in _English (US)_.
https://github.com/flathub/org.mozilla.Thunderbird#language-support

Lightning add-on
https://addons.thunderbird.net/addon/lightning

Calendar Versions
https://developer.mozilla.org/en-US/docs/Mozilla/Calendar/Calendar_Versions

If the Lightning version which works with the current Thunderbird version was available on [ATN](https://addons.thunderbird.net/addon/lightning), could that be incorporated into the Thunderbird flatpak? The ATN version seems to includes all the languages
https://addons.thunderbird.net/addon/lightning/versions/

What do you think?

Thank you

**Comment by Erick555** [comment]
Unfortunately the version from addon store [is broken](https://github.com/flathub/org.mozilla.Thunderbird/issues/86) so we have to keep bundled one.

The only known to me way to get localized calendars is to [extract them from every localized thunderbird tarballs published by mozilla](https://src.fedoraproject.org/rpms/thunderbird/blob/eb8931b4ab33c0185301a32b39d3e78ecb81ccff/f/get-calendar-langpacks.sh). Considering that there are 62(!) different locales and each tarball weight over 50MB this is way beyond our capabilities.

I hope some day Thunderbird will become multi-lang friendly but it's not today.

**Comment by darktrojan** [comment]
I've been working on this. Follow https://bugzilla.mozilla.org/show_bug.cgi?id=1588668 for progress.

> The only known to me way to get localized calendars is to extract them from every localized thunderbird tarballs published by mozilla. Considering that there are 62(!) different locales and each tarball weight over 50MB this is way beyond our capabilities.

That's what I'm doing too, except I'm doing it in the same place as the tarballs are generated so there's a lot less waiting for downloads.

**Comment by darktrojan** [comment]
Also, 68.1.2 is currently awaiting approval on addons.thunderbird.net.

**Comment by darktrojan** [comment]
I have no control over that.

**Comment by ovari** [comment]
> I have no control over that.

@darktrojan [Lightning 68.1.2](https://addons.thunderbird.net/addon/lightning/versions/68.1.2) is available on ATN. Thank you

> I hope some day Thunderbird will become multi-lang friendly but it's not today.

@Erick555 Has [Lightning 68.1.2](https://addons.thunderbird.net/addon/lightning/versions/68.1.2), available on ATN, enabled Thunderbird to become multi-lang friendly? If so, can you please update Thunderbird flatpak? Thank you

**Comment by ovari** [comment]
[Output lightning.xpi artifact from ESR68 builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1588659)

**Comment by darktrojan** [comment]
That bug is of no use to you, it's just en-US. It does enable the automatic building of multilingual Lightning though.

**Comment by Erick555** [comment]
@ovari as ATN versions don't have guarantee to work with latest TB release I'll keep bundled one. Users are free to replace it with version from ATN if that works for them.

**Comment by Erick555** [comment]
@darktrojan could you clarify current status? Is bundled calendar extension localized now and/or is there easier way to get localized version than what I described above?

**Comment by Erick555** [comment]
With TB 78.x calendar is build-in in app itself so this issue will be gone.
