### ISSUE TITLE
Automatically download and install dictionaries for languages available on the system

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#90]
> Dictionaries for languages other than English have to be downloaded manually from:
> https://addons.thunderbird.net/language-tools/
> and installed through:
> Menu Bar > Tools > Add-ons > Extensions > Install Add-on From File
> You may need to restart app in order to make changes effective.
https://github.com/flathub/org.mozilla.Thunderbird#language-support

Automatically download and install dictionaries for languages available on the system
https://bugzilla.mozilla.org/show_bug.cgi?id=1590916

What do you think?

@darktrojan do you have ideas on how this can be achieved?

Thank you

**Comment by darktrojan** [comment]
With the prefs `intl.multilingual.enabled` and `intl.multilingual.downloadEnabled` set to true the preferences tab can download language packs. I don't know how it works or the reason those prefs are set to false by default but that's probably a good starting point.

**Comment by ovari** [comment]
@darktrojan thank you for the references to the settings.

@Erick555 can these preferences be set in the flatpak version? Thank you

**Comment by Erick555** [comment]
AFAIK `intl.multilingual.enabled` will be set to `true` with FF/TB 69+. I wanted to keep upstream defaults but considering that runtime dictionaries doesn't seem working I may switch config with next update. It would still need manual user action though.

**Comment by ovari** [comment]
@Erick555 What manual user action is still required?

Would the implementation of this upstream request enable automatic download and install of dictionaries with no manual action required?
https://bugzilla.mozilla.org/show_bug.cgi?id=1590206

**Comment by Erick555** [comment]
@ovari actually I don't see enabling those two options having impact on dictionaries at all. I still have only English (US) and new one can be only downloaded from addon store.

**Comment by ovari** [comment]
@darktrojan does enable those two options have an impact on the dictionaries at all for you? Thank you

**Comment by darktrojan** [comment]
Oh, sorry I misread, for some reason I thought you were talking about language packs…

So to answer your actual original question, no, I don't know how that could be achieved. All I know is there's list of dictionaries, and it doesn't even contain all available dictionaries. https://addons.thunderbird.net/en-us/thunderbird/language-tools/

**Comment by ovari** [comment]
Automatically download and install dictionaries for languages available on the system
https://bugzilla.mozilla.org/show_bug.cgi?id=1590916

**Comment by Erick555** [comment]
Upstream closed the isue as WONTFIX so there is no thing we can do here.
